### ISSUE TITLE
Review Zetashapes-sourced US neighbourhood records

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1006]
Picking up where https://github.com/whosonfirst-data/whosonfirst-data/issues/1004 left off, other zetashapes-sourced neighbourhood records should be reviewed, too.

Any neighbourhood record with a `src:geom` of `zetashapes` should be reviewed (especially record with a large `geom:area`). These records do not have a `mz:tier_locality` property, so they were not caught in work done for #149.

**Comment by nvkelso** [comment]
If a neighbourhood doesn't have `mz:tier_locality` it didn't come from Quattroshapes and is sole-sourced from Zetashapes. Quattroshapes had a minimum threshold of Flickr photos it required to generate a polygons (somewhere in the 10 to 30 range), while Zetashapes didn't – resulting in very odd polygons.

Since we don't know where the neighbourhood is actually located, we may be better off deprecating them for now. If they can be proven with a point location from another source later we could un-deprecate them?

**Comment by stepps00** [comment]
There are 1,664 neighbourhood records in the US, sourced by Zetashapes with a `geom:area` over `.005`. Only ~100 of these records have a `mz:tier_locality` property, most equal to 1 or 5.

A few offenders:
https://whosonfirst.mapzen.com/spelunker/id/420550977
https://whosonfirst.mapzen.com/spelunker/id/420517717
https://whosonfirst.mapzen.com/spelunker/id/420521981
https://whosonfirst.mapzen.com/spelunker/id/420536063
https://whosonfirst.mapzen.com/spelunker/id/420534471

I will propose a PR that deprecates the neighbourhood records with obviously large geometries, then take a look at the rest, comparing them to surrounding neighbourhood records.

**Comment by stepps00** [comment]
I've marked 708 of these neighbourhoods as OK as-is, the remaining 956 records should be deprecated. 

Any neighbourhood with a `geom:area` under `.01` was marked as OK as-is, as were some records near urban cores.

**Comment by stepps00** [comment]
A couple more:

https://spelunker.whosonfirst.org/id/420549999/
https://spelunker.whosonfirst.org/id/420530003/

**Comment by stepps00** [comment]
This is related to https://github.com/whosonfirst-data/whosonfirst-data/issues/1258 and it's PR https://github.com/whosonfirst-data/whosonfirst-data/pull/1259. Looks like additional work is needed.
