### ISSUE TITLE
capital city regressions

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1027]
heya,

I just rebuilt one of our databases and noticed that there have been two regressions for our capital cities test suite.

The test suite runs through all the capital cities in the world and checks that the `locality` is correctly associated with its parent `country/dependency`.

The two which previously passed and now are failing are:

```
input:     West Island, Cocos Islands
expected:  890417321

input:     Mata Utu, Wallis and Futuna
expected:  890452045
```

In both cases the record previously had the correct `wof:hierarchy[0].country_id`, now it's set as `-1`.

Thanks!

**Comment by missinglink** [comment]
ref: https://github.com/whosonfirst-data/whosonfirst-data/blame/master/data/890/417/321/890417321.geojson#L40 (you can click the little boxes next to the line number 39 to see it prior)

**Comment by nvkelso** [comment]
I suspect this is a combination of geometry inconsistencies between the placetype levels in the desired hierarchy. We can either fix up the geometries (yes) and probably also set some reverse geo points since these shapes are irregular.

**Comment by stepps00** [comment]
Yeah, this is both a geometry and property issue. I'll investigate today and try to work through this in BI.

**Comment by stepps00** [comment]
The solution to this issue is a bit more complex than just updating the two linked records above. We have offset geometries and duplicate records, so I will propose a PR to fix this problem (instead of updating in BI).

To-dos:

- [ ] Update the [empire of France](https://whosonfirst.mapzen.com/spelunker/id/136253037) to include the geometry of [Wallis and Futuna](https://whosonfirst.mapzen.com/spelunker/id/85632585).
- [ ] Update the geometry of [`Uvea](https://whosonfirst.mapzen.com/spelunker/id/85680901) to include the more precise geometry in [Wallis and Futuna](https://whosonfirst.mapzen.com/spelunker/id/85632585).
- [ ] Update the geometry of [Matâ' Utu](https://whosonfirst.mapzen.com/spelunker/id/890452045) to be on the island of Wallis and Futuna.
- [ ] Update the [empire of Australia](https://whosonfirst.mapzen.com/spelunker/id/136253039/) to include the geometries of: [1](https://whosonfirst.mapzen.com/spelunker/id/404550157), [2](https://whosonfirst.mapzen.com/spelunker/id/404550149), [3](https://whosonfirst.mapzen.com/spelunker/id/404550151), [4](https://whosonfirst.mapzen.com/spelunker/id/874411115)
- [ ] Update the country of [Indian Ocean Territories](https://whosonfirst.mapzen.com/spelunker/id/85632495) to include the geometries of: [1](https://whosonfirst.mapzen.com/spelunker/id/404550157), [2](https://whosonfirst.mapzen.com/spelunker/id/404550149), [3](https://whosonfirst.mapzen.com/spelunker/id/404550151), [4](https://whosonfirst.mapzen.com/spelunker/id/874411115)
- [ ] Update the region of [Cocos (Keeling) Islands](85672275) to include the geometries of  [1](https://whosonfirst.mapzen.com/spelunker/id/404550157), [2](https://whosonfirst.mapzen.com/spelunker/id/404550149), [3](https://whosonfirst.mapzen.com/spelunker/id/404550151)
- [ ] Take care of duplicates: [West Island](https://whosonfirst.mapzen.com/spelunker/id/890417321) and [West Keeling Island](https://whosonfirst.mapzen.com/spelunker/id/101938929)

**Comment by stepps00** [comment]
@missinglink - we currently have two records for the West Island capital locality ([polygon](https://whosonfirst.mapzen.com/spelunker/id/101938929/), [point](https://whosonfirst.mapzen.com/spelunker/id/890417321/)). The PR for this issue will supersede 890417321 into 101938929, so your tests will need to be updated with a new `wof:id` to test. 

I will confirm this once the PR is merged..

**Comment by missinglink** [comment]
That's great thanks, no problem with superseding it.
