### ISSUE TITLE
deprecated records have descendants

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1040]
Heya,

I found a record marked as `deprecated` https://whosonfirst.mapzen.com/spelunker/id/102087933/

Which also has 52 descendants: https://whosonfirst.mapzen.com/spelunker/id/102087933/descendants/?exclude=nullisland

Is this correct? for some records to have a parent association which is deprecated?

**Comment by stepps00** [comment]
Thanks for the issue @missinglink 

No, that is not the expected behavior a deprecated record.. I'm noticing a few cases in Ukraine where descendant records were not updated when a `county` parent was updated. This should be a straight-forward fix using our PIP tools.

I'll poke around a bit more and propose a PR to fix.
