### ISSUE TITLE
India country is missing some regions

### ISSUE THREAD

**Issue by nlehuby** [whosonfirst-data/whosonfirst-data#1067]
The country record for India does not look ok, the following regions are missing:
- Lakshadweep region
- Andaman and Nicobar Islands region 
- Jammu and Kashmir

https://data.whosonfirst.org/856/324/69/85632469.geojson

**Comment by nvkelso** [comment]
Agree the polygon geometry for India isn't as expansive as it should be. Looks like the missing shapes are still included as child `region` records so those can probably just be cat'd onto the existing geom. Jammu and Kashmir will need separate attention due to their disputed status (there are a few outstanding issues tracking work like that already, I think).

- https://whosonfirst.mapzen.com/spelunker/id/85632469/descendants/?exclude=nullisland&placetype=region

**Comment by stepps00** [comment]
Hi @nlehuby - it looks like the regions you've listed above are indeed in Who's On First:

**Lakshadweep region**: https://spelunker.whosonfirst.org/id/85632275/
**Andaman and Nicobar Islands region**: https://spelunker.whosonfirst.org/id/85672175/
**Jammu and Kashmir region**: https://spelunker.whosonfirst.org/id/85672137/

**List of region descendants for India**: https://spelunker.whosonfirst.org/id/85632469/descendants/?exclude=nullisland&placetype=region

*Note that Jammu and Kashmir is not listed in the descendants page because it is disputed between India and China. 

Suggest closing this issue unless the region data still looks off in some way.

**Comment by nlehuby** [comment]
thanks :1st_place_medal:
