### ISSUE TITLE
Weird characters in German

### ISSUE THREAD

**Issue by tadjik1** [whosonfirst-data/whosonfirst-data#1069]
Hi there, we've found that from time to time german names have wrong encoding that leads to problems with german symbols (ä, ö, ü). For example:
https://whosonfirst.mapzen.com/spelunker/id/102063415/

**Comment by nvkelso** [comment]
Hi @tadjik1, thanks for letting us know about the character encoding problems. We've already fixed a good number of problems relating to that and will have a look at this latest report. But since Mapzen has shutdown our attention isn't full time. We're happy, of course, to accept a PR from you fixing the problem!

**Comment by tadjik1** [comment]
@nvkelso I would like to help with that! 
should I send PR directly to this repo or to somewhere else?

**Comment by nvkelso** [comment]
Directly in this repo, please :)

**Comment by tadjik1** [comment]
@nvkelso hi there,
PR related to this issue: #1076
