### ISSUE TITLE
Fix records (78 of them) with self-intersecting geometries

### ISSUE THREAD

**Issue by straup** [whosonfirst-data/whosonfirst-data#1071]
The following returns 78 records that yield `Self-intersection at or near point...` or `Ring Self-intersection at or near point...` according to GDAL:

```
import mapzen.whosonfirst.utils
import osgeo.ogr
import geojson
import sys

if __name__ == "__main__":

    data = sys.argv[1]
    crawl = mapzen.whosonfirst.utils.crawl(data, inflate=True)

    for f in crawl:

	poly = osgeo.ogr.CreateGeometryFromJson(geojson.dumps(f['geometry']))
	valid = poly.IsValid()

	if not valid:
            print "%s %s" % (f['properties']['wof:id'], valid)
```

The complete list is attached but you can see an example here:

https://whosonfirst.mapzen.com/spelunker/id/85766257/

cc @simonw

[report.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1624705/report.txt)

**Comment by straup** [comment]
@nvkelso @stepps00 do you have any #feelings about this:

```
# https://pcjericks.github.io/py-gdalogr-cookbook/geometry.html#calculate-union-between-two-geometries

union = poly.Union(poly)
valid = union.IsValid()
print "%s is valid now? %s" % (f['properties']['wof:id'], valid)
```

Which appears to work for most of the cases, but not all:

```
Warning 1: Ring Self-intersection at or near point 23.32946777340004 42.662241376300059
85929283 False
85929283 is vaild now? True
Warning 1: Ring Self-intersection at or near point 73.883056640599989 18.547324589800041
85903913 False
85903913 is vaild now? True
Warning 1: Self-intersection at or near point -71.067631452227474 42.369007985580474
85950361 False
ERROR 1: TopologyException: Input geom 0 is invalid: Self-intersection at or near point -71.067631452227474 42.369007985580474 at -71.067631452227474 \
42.369007985580474
Traceback (most recent call last):
  File "./test.py", line 25, in <module>
    valid = union.IsValid()
AttributeError: 'NoneType' object has no attribute 'IsValid'
```

See also: 

* https://gis.stackexchange.com/a/62990
* http://workshops.boundlessgeo.com/postgis-intro/validity.html#repairing-invalidity

**Comment by thisisaaronland** [comment]
There are in fact more than 78 invalid geometries (closer to a few thousand I think) and I am regenerating that list now using: 

https://github.com/whosonfirst/py-mapzen-whosonfirst-validator/blob/master/scripts/wof-validate-geometry

The following are known to cause fatal errors when importing in to MySQL (or put another way: the other invalid geometries do _not_ trigger errors) but can be fixed with `shapely.buffer(0)`... which the exception of Pongola which is a line that should be replaced by a point:

```
85668045    La Rioja
85670185    Cauca
85671757    East Berbice-Corentyne
85672205    Uttar Pradesh
85679819    Pallisa
85687215    Chatham Islands
85977539    New York
101927443    Pongola
102191569    Asia
102191575    North America
772967579    Broadway
1126058431    Old Ottawa
```

**Comment by nvkelso** [comment]
I’m fine with applying a 0 buffer and the usual host of “just make it
valid” tricks here.

On Fri, Jan 12, 2018 at 2:42 PM, Aaron Straup Cope <notifications@github.com

**Comment by straup** [comment]
One day I will figure out Java (and by extension JTS)... 

https://github.com/aaronland/java-whosonfirst-geojson

**Comment by stepps00** [comment]
```
...
    for feature in crawl:
        props = feature['properties']
        geom = feature['geometry']

        poly = osgeo.ogr.CreateGeometryFromJson(geojson.dumps(geom))
        valid = poly.IsValid()

        if not valid:
            print props['wof:id']
```

I reran a crawl for invalid geoms, which resulted in 1455 ids of records with invalid geometries.

Full list here: [list_of_invalid_geoms.txt](https://github.com/whosonfirst/whosonfirst-cookbook/files/2320118/list_of_invalid_geoms.txt)

Invalid geometries are due to:
  - `Self-intersection`
  - `Ring Self-intersection`
  - `Hole lies outside shell`
  - `Too few points in geomtry component`
  - `Nested shells`
  - `Duplicate Rings`

I tried the `buffer(0.0)` trick, but this causes some of the self-intersecting geometries to become null (`POLYGON EMPTY`) and ogr validates null polygons, so..

I'm looking into the best method to split off outer rings correctly and rewrite polygons. I'll flag this issue once a PR is filed with a fix.

It would also be nice to validate geometries for any new/updated records in this repo, maybe that involves wiring a geometry validation check into the export code?
