### ISSUE TITLE
"Broadbench" is a neighborhood in Queensland, Australia with country and region set to -1

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#1075]
https://whosonfirst.mapzen.com/spelunker/id/85768937/

![2018-01-29 at 7 10 am](https://user-images.githubusercontent.com/9599/35517522-8a3643b8-04c3-11e8-82d3-24faf32a441e.png)

It's a perfectly reasonable looking polygon:

![2018-01-29 at 7 11 am](https://user-images.githubusercontent.com/9599/35517535-9a54f154-04c3-11e8-8fff-70c95bbe80f4.png)

Could this be because the neighborhood polygon centroid falls just off the shore and hence isn't within the region and country polygons?

**Comment by nvkelso** [comment]
Yes, that’s most likely.

There are a few ways to fix this. The simplist is to add a revgeo centroid for pip to the neighbourhood and repip it. Or just fix the overall shape so it’s more rational to its parent.

Alternatively the “parent” shapes can have revgeo polys added that extend out into the water.

**Comment by stepps00** [comment]
Noting here that this is being caused by the centroid lat/long for Queensland being _just_ outside of the geometry for the [Gold Coast](https://spelunker.whosonfirst.org/id/102049363/). An easy fix is to add a `reversegeo:latitude` and `reversegeo:longitude` property to the Queensland record and re-PIPing.
