### ISSUE TITLE
Correcting incorrect venue sg:classifiers?

### ISSUE THREAD

**Issue by reidab** [whosonfirst-data/whosonfirst-data#1090]
I've been working with the WOF US venue data on a recent project and am curious if there's a process for correcting records with incorrect category information in `sg:classifiers`, such as [this construction company masquerading as a campground](https://places.whosonfirst.org/id/756644071).

If it's useful, I can generate an export of a bunch of records that claim to be campgrounds but are really other things.

**Comment by stepps00** [comment]
Hey @reidab - thanks for the issue. A general rule for WOF is that we will keep any source properties as-is. We use the `sg` prefix to catalogue what SimpleGeo has classified a given record as. If we used these classifiers in `wof:*` properties or sourced them for another property, they should not be used if we know they are correct, though.

If you are willing to export a list of these campgrounds, we can validate that SimpleGeo does in fact classify these records as campgrounds, otherwise we will probably keep as is -- or use a marker like [`mz:is_funky`](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/mz/is_funky.json) to flag these records as bad in some way.

**Comment by nvkelso** [comment]
We do have plans around our own WOF categories, which would be populated initially based on the SG classifiers – but like @stepps00 said we don't plan on modifying the `sg` prefixed properties directly.

**Comment by reidab** [comment]
That makes sense — I'd kind of assumed that you were trying to keep the `sg:` scope true to the original SimpleGeo dataset. 

It seems like it may be useful to have a general marker of "this place is probably fine, but the categorization seems wrong" if [whosonfirst-categories](https://github.com/whosonfirst/whosonfirst-categories) properties start being applied to venue records.

Looking at the stuff I can easily extract from our system, it may not be as useful as I'd originally thought. The SimpleGeo classification of `Campground` seems to include things like summer camps and retreat centers, both of which get flagged as "not a campground" by our heuristics.

**Comment by stepps00** [comment]
Nothing actionable at the moment, so closing issue.
