### ISSUE TITLE
fix name of localadmin:Picton (NSW) to remove NSW indicator

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#110]
source: quattroshapes

```
"localadmin": "Picton (NSW)"
```

the state name is not required as part of the label

id: `qs:localadmin:1875`

**Comment by nvkelso** [comment]
This isn't in Who's On First (yet, it should be). Once it has been imported, than we can fix the record up.

We'd been thinking we should store a proper `label` (see this [document](https://github.com/whosonfirst/whosonfirst-names/blob/master/LABELS.md)) for a feature in addition to the `name`, but had been thinking that would be more for a full name (with all the hierarchy). Seems like the name itself should also have a label (because in some situations it is helpful to have `Picton (NSW)` when printing a long list of place names alone (without their parent region, & etc).

**Comment by nvkelso** [comment]
Blocked by import of said data: https://github.com/whosonfirst/whosonfirst-data/issues/112

**Comment by nvkelso** [comment]
This isn't blocked anymore.

**Comment by stepps00** [comment]
Closing issue, https://github.com/whosonfirst-data/whosonfirst-data/pull/1140 was merged :tada:
