### ISSUE TITLE
Add concordance with Wikipedia pages for places

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#113]
Looks like GeoNames.org has some of this as language code `link` and refreshes their concordance occasionally.

Wikipedia has useful words, pictures, and stats (especially population) about places. But this issue is just about adding concordance.

**Comment by thisisaaronland** [comment]
We already do this for airports, using the `wk:page` key:

http://whosonfirst.mapzen.com/spelunker/id/102534365/

**Comment by riordan** [comment]
Geonames concordances should provide a good scaffolding for this as well.

**Comment by almccon** [comment]
Maybe I missed it and you've already considered this, but instead of Wikipedia pages perhaps you should link to Wikidata pages? https://www.wikidata.org/wiki/Q8685 is referenced from within https://en.wikipedia.org/wiki/John_F._Kennedy_International_Airport, for example. And I think the long term plan for Wikipedia is to have its pages derived from Wikidata entries as much as possible.

**Comment by riordan** [comment]
:+1:

**Comment by thisisaaronland** [comment]
@almccon is there a lookup service for Wikipedia pages and Wikidata IDs? I had originally planned on eventually mapping the page (Wikipedia) URLs to page IDs but I am not wed to that idea.

**Comment by nvkelso** [comment]
@okavvada has made some progress on this already. Assigning this to her to track work over the next few weeks.

**Comment by nvkelso** [comment]
Subtask: https://github.com/whosonfirst/whosonfirst-data/issues/343.

**Comment by nvkelso** [comment]
More subtasks:

- #344 Add wikidata concordances
- #345 Add wikipedia page titles concordances
- #346 Add multiple language names from Wikipedia

**Comment by nvkelso** [comment]
This was completed :)
