### ISSUE TITLE
[Status: Ready for Merge] Philippines: Erroneous hierarchy and labels in National Capital Region

### ISSUE THREAD

**Issue by noizde** [whosonfirst-data/whosonfirst-data#1214]
- [City of Makati](https://spelunker.whosonfirst.org/id/1108697351/)
  - Description: This is encoded as a child of another city, the region entity labeled [Quezon City](https://spelunker.whosonfirst.org/id/1108697351/). On the other hand, its geometry is actually _bigger_ than Quezon City, and corresponds to what is locally known as the National Capital Region, which isn't reflected anywhere in the hierarchy. There's a separate [entity](https://spelunker.whosonfirst.org/id/85676413/), a region simply called Makati, that contains a shape actually corresponds to the actual city's administrative boundaries.
  - Suggestions:
    - Rename to National Capital Region
    - Change placetype to `region`
    - Set parent to [Philippines](https://spelunker.whosonfirst.org/id/85632509/)
- Cities within the National Capital Region
  - Description: 
    - There are entities that refer to actual cities within the National Capital Region (e.g. [Quezon City](https://spelunker.whosonfirst.org/id/85676395/), [Marikina](https://spelunker.whosonfirst.org/id/85676399/), [Pasay](https://spelunker.whosonfirst.org/id/85676415/)), but they're designated as `regions` and direct children of the Philippines country entity.
    - There are separate entities (e.g. [Marikina](https://spelunker.whosonfirst.org/id/421200223/), [Pasay](https://spelunker.whosonfirst.org/id/1141907273/)) that are designated as `localities` that seem to be duplicates, without any shapes.
    - These are labeled "National Capital Region" according to their `eng_x_preferred` values.
    - The above leads to some bizarre hierarchies: 
![image](https://user-images.githubusercontent.com/1861687/41025986-e46c3346-69a5-11e8-8852-e1010c20cbf3.png)
  - Suggestions:
    - Change these entities' placetypes from  `region` to `locality`, as per the [placetype guidelines](https://github.com/whosonfirst/whosonfirst-placetypes#locality).
    - Change their parents to [this](https://spelunker.whosonfirst.org/id/1108697351/) which seems to correspond to the National Capital Region.
    - Less a suggestion and more a question: it also seems appropriate to deduplicate and merge the data for the existing localities (so, say, merge [Marikina](https://spelunker.whosonfirst.org/id/85676399/) and [Marikina](https://spelunker.whosonfirst.org/id/421200223/)). Is there any accepted best practice or protocol for doing so?

**Comment by stepps00** [comment]
This is great, thanks @noizde. I'll take a look at the records in WOF and propose a PR fix.

To answer your last question, we use the [`wof:superseded_by`](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/superseded_by.json) and [`wof:supersedes`](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof/superseded.json) properties to link duplicate records together (the current record superseding the outdated or incorrect record) to indicate it is no longer current. When fixing duplicate records, we:

- Add `wof:supersedes` `wof:superseded_by` link
- Flag the non-current record with a `0` value in `mz:is_current`
- Flag the non-current record with a date in the relevant `edtf:*` property
- Add the non-current record's geometry as an alt-geometry

I have opened [an issue](https://github.com/whosonfirst/whosonfirst-cookbook/issues/23) in our `whosonfirst-cookbook` repo to describe this work, since it is a fairly common workflow and is not documented there. Stay tuned.

**Comment by noizde** [comment]
Great, thanks for the quick reply @stepps00! The hierarchies for local government units within the NCR are slightly different from the ones surrounding it, so I'd be happy to help disentangle that data.

**Comment by noizde** [comment]
I'm currently looking at the [Caloocan](https://github.com/whosonfirst-data/whosonfirst-data/tree/master/data/856/763/83) record, in order to generate the alt-geometry from the [record it supersedes](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/421/191/573/421191573.geojson). If I understand the [cookbook](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/creating_alt_geometries.md) correctly, this would normally result in an alt-geometry with the filename `85676383-alt-quattroshapes.geojson`, except there already exists one from the same source -- according to their `src:geom` values, they both come from `quattroshapes`.

The [existing one](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/856/763/83/85676383-alt-quattroshapes.geojson) uses a `MultiPolygon` geometry, while the to-be-superseded record has only a `Point` geometry. In this instance, should the newer one be identified additionally by that feature, i.e. named  `85676383-alt-quattroshapes-point.geojson`?

**Comment by stepps00** [comment]
@noizde - Thanks, this is a useful test case for saving multiple geometries from the same source. There are a few methods to tackle this, but I would suggest the following:

Quattroshapes `Point` geometries can be stored using the source [`quattroshapes_pg`](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/quattroshapes_pg.json) (Quattroshapes Point Gazetteer). The original import of these points did not differentiate between `quattroshapes` and `quattroshapes_pg`, but I think you'd be safe in saving the point geometry as an alt with the name `85676383-alt-quattroshapes_pg.geojson`.

Alternatively, you could link the two records using the `wof:supersedes` and `wof:superseded_by` properties without storing the point as an alt file.

**Comment by noizde** [comment]
I've submitted a pull request (#1220) that should address the issues I've noted above.

**Comment by nvkelso** [comment]
Looking at ISO here https://en.wikipedia.org/wiki/ISO_3166-2:PH I think the **National Capital Region** should be added as a WOF `macroregion` placetype (along with the other 16 at that level).

Then because **Quezon City** is both a `locality` within the National Capital Region and a top level WOF `region` we want to represent that with 2 WOF records and mark them as coterminous because they are 2 fundamental placetype levels in Who's On First but really the same feature.

@stepps00 Can you work with @noizde to update the PR in https://github.com/whosonfirst-data/whosonfirst-data/pull/1220, please? Don't both to update the wof:hierarchy, wof:belongs to, and wof:parent properties, we'll take care of that during PIPing.

**Comment by stepps00** [comment]
What's been suggested in https://github.com/whosonfirst-data/whosonfirst-data/issues/1214#issuecomment-398565648 is correct. The associated PR completes this work, but since placetypes are changing, we need to supersede existing records into new records (instead of replacing placetypes).

New PR incoming.
