### ISSUE TITLE
Figure out which is the what (this GeoNames ID or that one)

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#122]
When bringing over more GN.org concordances from the Quattroshapes gazetteer, we have around ~100 records that could be one GN id, or they could be another. Figure it out.

**Comment by nvkelso** [comment]
[mismatch.txt](https://github.com/whosonfirst/whosonfirst-data/files/18118/mismatch.txt)

**Comment by nvkelso** [comment]
(In the meantime, the one already in WOF will be preferred.)

**Comment by stepps00** [comment]
Long tail of crazy... bookmarking for a rainy day.

**Comment by stepps00** [comment]
I think we've "solved" this during the QS point gazetteer import, by storing the "mismatching" ids in the `qs:id` and `qs_pg:id` concordances. Unsure if this has to do with GeoNames. 

For example, https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/101/913/145/101913145.geojson

`MISMATCH 101913145 (wofid) 1151437 (ours) 502526 (theirs)`

This record has the `1151437` id stored in the `qs:id` concordance and the `502526` id stored in the `qs_pg:id` concordance.

Fine with keeping this open, but we can probably close since we have the following actionable QS issue open; https://github.com/whosonfirst-data/whosonfirst-data/issues/376. There are also various GeoNames clean-up issues open.
