### ISSUE TITLE
Incorrect names for 85835959

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1248]
The [neighbourhood of Multnomah](https://spelunker.whosonfirst.org/id/85835959/) (not to be confused with the [County of Multnomah](https://spelunker.whosonfirst.org/id/102081631/)) is incorrectly named:

```
"name:ido_x_preferred": [
  "Portland"
],
"name:isl_x_preferred": [
  "Portland"
],
"name:ita_x_preferred": [
  "Portland"
],
"name:jpn_x_preferred": [
  "ポートランド"
],
... etc
```

It seems to have inherited it's names from the locality?

**Comment by stepps00** [comment]
Thanks @missinglink - looks like this is coming from a bunk GeoNames concordance value.. 

http://www.geonames.org/5746545/

When #874 was completed, it relied on the GeoNames concordance values when adding name translations; in this case the concordance is wrong (links to Portland, instead of Multnomah), meaning we imported translations for Portland.

I'll correct the concordance value and update the `name:*` properties with the correct translations.

**Comment by stepps00** [comment]
Fixed in https://github.com/whosonfirst-data/whosonfirst-data/pull/1253, closing.
