### ISSUE TITLE
Fracc Jardin - which state/country is it in?

### ISSUE THREAD

**Issue by nigelhorne** [whosonfirst-data/whosonfirst-data#1249]
I'm trying to work out what state Fracc Jardin is in.

https://spelunker.whosonfirst.org/search/?q=Fracc+Jardin

I isn't clear to me.  In OpenStreet maps it's listed as being in Mexico, but in WOF it's listed as being in the US.

**Comment by nvkelso** [comment]
It should be Mexico but reports incorrectly as USA. This is because the reverse geocoding point for this polygon feature is undefined so the fallback logic we used for Point in polygon logic a long time ago defaulted to the math centroid which is in USA while newer logic uses label centroid when available (it is here) which is in Mexico.

**Comment by stepps00** [comment]
Thanks for the issue @nigelhorne - as @nvkelso mentioned above, this record should be in Mexico. 

The hierarchy shows Mexico as the correct parent country, but the country codes are incorrectly tagged as "US".

**Comment by stepps00** [comment]
Fixed in https://github.com/whosonfirst-data/whosonfirst-data/pull/1253, closing.
