### ISSUE TITLE
Move data into Wikidata?

### ISSUE THREAD

**Issue by davidbarratt** [whosonfirst-data/whosonfirst-data#1284]
Just opening this up for discussion... but perhaps [Wikidata](https://www.wikidata.org) could be the new home for all of this data?

The references to the other databases would be preserved. I don't think there is a field currently for geometry (geoJSON), but I don't see why that couldn't be added (as well as fields for all of the other data points, like hierarchy).

What do you think? is this a crazy idea?

**Comment by davidbarratt** [comment]
Oh! it's _already_ in CC0. Well how lovely. I guess my question is... is there way to identify what pieces of data are freely licensed and which ones are not?

**Comment by davidbarratt** [comment]
Also... if you cannot copyright _facts_ about something, then can any of the data actually be copyrighted in the first place?

**Comment by thisisaaronland** [comment]
The data is _effectively_ CC-BY by virtue of the data that WOF imports. The work that WOF itself does is CC-0.

We don't do row/column level attribution. I thought about it long enough to recognize a giant pool of quicksand filled with yak hair :-) It would be interesting, as an exercise, to spin up an instance of Accumulo with WOF data and see how that would work but it's enough just working with the data as-is...

The geometries should all have sources/attributions which will have a corresponding entry in the `whosonfirst-sources` repo, which contains licensing information.

As for Wikidata, it's a different beast. We are happy to add concordances to and from Wikidata (as evidenced by @ImreSamu 's awesome work) but the concerns and mechanics are not the same.

**Comment by thisisaaronland** [comment]
Also, I closed the issue mostly for the sake of other people working on outstanding issues but I am happy to continue any conversation here.

**Comment by davidbarratt** [comment]
what are the differences in concerns and mechanics that you see?

**Comment by thisisaaronland** [comment]
RDF, for starters and the barrier to entry that this presents in terms of approach-ability and tooling in general. I have nothing against triples in principle (I was deeply involved with all the machine tags stuff at Flickr :-) and WOF tries to build on all the good parts of RDF without all the weird stuff.

We chose GeoJSON for the specific reason(s) that it's the least amount of markup for meaningful structured data available today coupled with the fact that JSON is natively supported in every language out there and GeoJSON is easily transformed in to (and from) all the other geo formats, using readily available tools.

That's relevant for us because while there is growing support for GeoJSON in the applications best suited for editing geometries the reality is that most of them work best and traffic in Shapefiles.

We chose atomic self-contained records because the _failure_ scenario for WOF is to open up a document in Notepad (or whatever) and edit it by hand. It's not ideal, especially if you have to update a lot of files, but it does work. The last time I checked the Wikidata dump is the size of a small planet and requires non-trivial resources to stitch it back together.

Finally, WOF is just "all of the places" and Wikidata is "everything" :-)

**Comment by davidbarratt** [comment]
FYI There is now a property to link Wikidata items to Who's on First: https://www.wikidata.org/wiki/Property:P6766

**Comment by nvkelso** [comment]
@davidbarratt thanks for the update, very exciting!

**Comment by ImreSamu** [comment]
Thanks!  
* And the Wikidata BOT is :)   https://www.wikidata.org/wiki/User:Q23679   
* history : https://www.wikidata.org/wiki/Special:Contributions/Q23679 
* Source code : https://github.com/whosonfirst-wikidata/bot
  * https://github.com/whosonfirst-wikidata/bot/blob/master/index.js
  * input data `https://dist.whosonfirst.org/sqlite/....`  -> https://dist.whosonfirst.org/sqlite/

**Comment by ImreSamu** [comment]
@davidbarratt :

imho:
* Be careful with updating wikidata items - with "WOF placetype info" or  other info from WOF!
  * (https://github.com/whosonfirst-wikidata/bot/blob/master/index.js#L21 )

Reason:
* the WOF placetypes mostly  not has 1:1 relationships with the wikidata categories  ...  (  imho it is :  `1:N` )
    * the extreme example:   wikidata 'campus' ['Q209465'](https://www.wikidata.org/wiki/Q209465)    **!=**   wof 'campus'  ( mostly airports/aerodrome,  spaceport ,  rocket launch site , ...)

When I researched .. the WOF campus - Wikidata matching was:
*  https://github.com/whosonfirst/concordances-whosonfirst-wikidata/blob/master/code/wikidata_campus.csv

**Comment by davidbarratt** [comment]
so... I did this because of a [some](https://www.wikidata.org/wiki/Topic:V613otbdv40m4be0) [complaints](https://www.wikidata.org/wiki/Topic:V68x0yd76lxw2set).

I do look up anything that extends that type, so it's actually a lot bigger than that list:
```
Class Q319608 is subclassed by 5 items
Class Q11315 is subclassed by 13 items
Class Q5195043 is subclassed by 17 items
Class Q41176 is subclassed by 4,283 items
Class Q209465 is subclassed by 4 items
Class Q862212 is subclassed by 1 items
Class Q192611 is subclassed by 753 items
Class Q5107 is subclassed by 6 items
Class Q6256 is subclassed by 77 items
Class Q28575 is subclassed by 90 items
Class Q161243 is subclassed by 63 items
Class Q15239622 is subclassed by 8 items
Class Q48349 is subclassed by 11 items
Class Q5375483 is subclassed by 1 items
Class Q20437094 is subclassed by 10 items
Class Q285783 is subclassed by 25 items
Class Q66941850 is subclassed by 1 items
Class Q486972 is subclassed by 1,504 items
Class Q66980082 is subclassed by 1 items
Class Q66980180 is subclassed by 1 items
Class Q3434769 is subclassed by 3 items
Class Q66980635 is subclassed by 1 items
Class Q6770790 is subclassed by 1 items
Class Q1907114 is subclassed by 15 items
Class Q66980952 is subclassed by 1 items
Class Q123705 is subclassed by 323 items
Class Q9430 is subclassed by 6 items
Class Q634 is subclassed by 48 items
Class Q37447 is subclassed by 27 items
Class Q3455524 is subclassed by 28 items
Class Q12143 is subclassed by 4 items
Class Q17350442 is subclassed by 1,256 items
Class Q1125776 is subclassed by 3 items
```

and then I take the list of **all** of those and ensure that it implements at least **one** or **none** if it doesn't match any, then something is probably wrong and I move on.

If campus (or whatever) is a different concept, I think it's fine to create a new base for everything to extend from (and we could use your research to figure out what should extend from this base). Though perhaps it should be called something else?

I would like to get URIs for the placetypes in WOF (see whosonfirst/whosonfirst-placetypes#21) that way I can map the classes in Wikidata to the classes in WOF with [equivalent class](https://www.wikidata.org/wiki/Property:P1709). Even if that means a new class should be created.

**Comment by davidbarratt** [comment]
Let me know if you have any better ideas for how to prevent the bot from editing something that... clearly isn't something that would be in WOF.

**Comment by nvkelso** [comment]
How often does the bot run?

When the WOF SQLite files are updated, will the bot automatically pick those up on a cadence? 

How many wikidata records now have a WOF ID concordance?

**Comment by ImreSamu** [comment]
@davidbarratt: 
- `const placetypes = ..`   ...  OK ;  so it is only a safety belt .. :)  Thank you for the info! 
- ( ~ the end of the year )   I try to create an   "wof placetype - wikidata class (1:n)"  meta table. ( https://github.com/whosonfirst/whosonfirst-placetypes/issues/21 )  
    -    ( and I need to update [my code](https://github.com/whosonfirst/concordances-whosonfirst-wikidata)  -  because the wof data repo is seperated )

**Comment by davidbarratt** [comment]
> How often does the bot run?

So here's my plan:
- [x] `wd:id` concordance (in wof) to Wikidata item
- [ ] `gn:id` concordance (in wof) to Wikidata item via [GeoNames ID](https://www.wikidata.org/wiki/Property:P1566) (in progress)
- [ ] `gp:id` concordance (in wof) to Wikidata item via [WOEID](https://www.wikidata.org/wiki/Property:P1281)
- [ ] some other concordance that both projects share?
- [ ] add the [spelunker](https://spelunker.whosonfirst.org/) to [Mix'n'match](https://tools.wmflabs.org/mix-n-match/) to allow the community to manually match/create new items in Wikidata. Or if that's a bad idea, maybe making a new tool to better manually match the items.

> When the WOF SQLite files are updated, will the bot automatically pick those up on a cadence?

Everytime I run it, it checks for updates. But after the initial matching is done, I'm not sure what the point would be of running it again...? I did just add some code that lets it start from where it left off, so I could set it up to try and match anything new (through the above concordances) whenever the dumps are updated... It seems that that wouldn't often result in an automatted match though...

> How many wikidata records now have a WOF ID concordance?

You can find that with this search query: https://www.wikidata.org/w/index.php?search=haswbstatement%3AP6766&title=Special%3ASearch&ns0=1
which has a current result set of `547,661`

> ( ~ the end of the year )   I try to create an   "wof placetype - wikidata class (1:n)"  meta table. ( [whosonfirst/whosonfirst-placetypes#21](https://github.com/whosonfirst/whosonfirst-placetypes/issues/21) )

That would be awesome! also, if you want them bi-directional (which isn't really necessary as I think it's fine if it's only linked _from_ Wikidata, but might be nice anyways) I created a PR for that: whosonfirst/whosonfirst-placetypes#22

**Comment by ImreSamu** [comment]
@davidbarratt :
( sorry my raw english ) 

> So here's my plan: ....

my personal **STRONG opinion** and we need discussing   :  
*  please don't add other concordances from the WOF ! ( 'gn:id' ; 'gp:id' ; 'some other concordance that both projects share' )  without discussing! 
*  on the other hand :  Data Quality reports WELCOME!   


imho : 
* the [unintended consequences](https://en.wikipedia.org/wiki/Unintended_consequences) -->  We can't clean and compare the 2 databases ....  because your bot importing every concordances (good and bad) from WOF.  so there will be no differences !      
* now the wikidata is used 
     *  as a reference (compare and clean)
     *  and importing some values  (mostly Labels) ...
* the wof-wikidata concordances status:
     *   need more cleaning ; ( adding; removing; modifying )  - and lots of low hanging fruits ... and know problems.
* data cleaning is 100x harder task   than importing ...

For example - my  practice  -  for cleaning the Airport data:
compare `Wikidata` - `WOF` - `OurAirports` databases - and check the differences (`iata`;`icao`; `faa` ; GPS; names/labels ; ) 
and fix the WOF and  fix the WIKIDATA values (manually;if easy)  ...
* https://github.com/whosonfirst-data/whosonfirst-data/pull/1375
* https://github.com/whosonfirst-data/whosonfirst-data/pull/1388
* https://github.com/whosonfirst-data/whosonfirst-data/pull/1419
* https://github.com/whosonfirst-data/whosonfirst-data/pull/1418
* https://github.com/whosonfirst-data/whosonfirst-data/pull/1417
* ....

So if you are adding airport concordances ("blindly") to Wikidata -   you are hiding the data problems;  and we can't detect easily! 


The other example is adding geonames('gn:id') concordances from WOF to Wikidata  - probably will have a negative impact for both project (the  Wikidata and the WOF data quality) !
* 'known known' - bad wikidata concordances exist in the WOF databases
* the new (never perfect)  algorithm for find - concordances ; based on Wikidata Labels; GPS distances; wikidata properties\classes 
* IF your bot import the  'gn:id' concordances to Wikidata AND  the [other bots](https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot) - adding blindly - the (incorrect) labels\GPS coords from Geonames to the Wikidata ( based on (incorrect)  'gn:id' from WOF )
* THEN we can't  detect the differences  AND we can't correct the wikidata concordances ; 
* RESULT1:  negative impact for the Wikidata data quality
* RESULT2:  negative impact for the WOF data quality

The other extreme example:
* STEP1:   your bot : add wof concordances to wikidata 
* STEP2:   your bot : add  'gn'(geonames) from wof
* STEP3:   other wikidata bot :  find the new `gn`  ; and import geonames labels ; gps positions  to Wikidata 
* STEP4:   wof:  the concordances updated with the correct values 
* STEP5:   your bot:   removing the  STEP1/STEP2 data ...
* QUESTION:  But how we can remove the STEP3 labels from Wikidata?  What is the process ?
* STEP6:    wof:  we find the STEP3 data in the wikidata ; and undo STEP4  because our  scoring algorithm  prefer labels/GPS  :( 
* STEP7:    your bot : add STEP1/STEP2 data again ...
 
imho:
* we need to analyze the full lifecycle and cascading effects  with a consequences !

**Comment by davidbarratt** [comment]
The only thing the bot does is add [Who's on First ID](https://www.wikidata.org/wiki/Property:P6766) to **existing** Wikidata items:
https://github.com/whosonfirst-wikidata/bot/blob/8a7a84ad89671a9e29e60586651446e15a83ee9e/index.js#L506-L522

and that is the only thing it is currently [authorized to do](https://www.wikidata.org/wiki/Wikidata:Requests_for_permissions/Bot/Q23679).

It does **not** edit other properties, nor does it create new items.

I hope this clarifies things.
