### ISSUE TITLE
Country shapes from Natural Earth are too coarse for default

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#1318]
Looking at Ireland the default geometry is from Natural Earth which is quite coarse. 

This creates problems for PIP hierarchy along the shore / international boundaries: https://spelunker.whosonfirst.org/id/85685015/.

We should remake these polygons, probably by dissolving the child regions and then use Mapshaper to get them under 3 mb.

![image](https://user-images.githubusercontent.com/853051/45646860-5a15fe00-ba79-11e8-9c83-6b115f613fad.png)

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/991

**Comment by stepps00** [comment]
Comparison of existing and potential geometry precision for Ireland:

**Existing NaturalEarth geometry:**
<img width="552" alt="existing" src="https://user-images.githubusercontent.com/18567700/45897706-b97f5100-bd8c-11e8-9144-13c53a930ff8.png">

**Existing Quattroshapes alt-geometry:**
<img width="604" alt="quattroshapes" src="https://user-images.githubusercontent.com/18567700/45897707-ba17e780-bd8c-11e8-97ab-b42790ebbd9c.png">

**Dissolved regions:**
<img width="651" alt="regions_dissolved" src="https://user-images.githubusercontent.com/18567700/45897708-ba17e780-bd8c-11e8-8653-65fbaef59688.png">

**Dissolved regions, simplified to 3mb using Mapshaper (`-simplify 5%`):**
<img width="580" alt="simplified_5percent" src="https://user-images.githubusercontent.com/18567700/45897705-b97f5100-bd8c-11e8-8336-43e01af503a5.png">

It clearly lookks like the best option for the Ireland country geometry is to merge all regions into a single geometry and Mapshaper down to 3mb. Ireland is a special case, though, since we recently updated geometries from the [Ordnance Survey Ireland](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/ie-gov.json). We have 47 country geometries sourced from NaturalEarth, so I'll update on a case-by-case basis, but likely follow the same workflow as Ireland.

**Comment by nvkelso** [comment]
Great screenshots showing the options, thanks!

**Comment by thisisaaronland** [comment]
Smells like a blog post...

**Comment by stepps00** [comment]
Closed via #1321
