### ISSUE TITLE
Missing locality: Fairfield, CT, USA

### ISSUE THREAD

**Issue by riordan** [whosonfirst-data/whosonfirst-data#133]
Locality of the Town of Fairfield appears to be missing.

We have Neighbourhoods in Fairfield ([Tunxis Hill](https://whosonfirst.mapzen.com/spelunker/id/85852811/) and the county ([Fairfield County](https://whosonfirst.mapzen.com/spelunker/id/102084283/)), but not the town.

This is not one of those situations where the town is coterminus with the county (e.g. SF City ~= SF County), but rather where the town is one of many in the county of the same name.

**Comment by nvkelso** [comment]
Smells like a `localadmin`.

**Comment by riordan** [comment]
Sadly, it's a full-on Locality. The localadmin it contains is [southport](https://whosonfirst.mapzen.com/spelunker/id/85930959/)

**Comment by nvkelso** [comment]
We're missing all the New England `minor civil divisions`, which is the US Census storage for [Towns](https://en.wikipedia.org/wiki/New_England_town#Towns). 

We should **not** import those for all USA places, just for states that use them (probably less than 10 of them, including New Jersey).

**Comment by riordan** [comment]
Oh the legacy of Puritans...

**Comment by riordan** [comment]
@nvkelso you were absolutely right that it's [in there as a localadmin](https://whosonfirst.mapzen.com/spelunker/id/404495947/), which is strange, because the other towns in the county are listed as Localities. 

If I had to guess, I'd say [Southport](https://en.wikipedia.org/wiki/Southport,_Connecticut) which used to be a separate administrative borough, but is listed as a [locality](https://whosonfirst.mapzen.com/spelunker/id/85930959/) in WoF, when it would more appropriately be classified as a localadmin.

**Comment by stepps00** [comment]
Fairfield locality: https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/172/944/047/3/1729440473.geojson

I believe this issue was fixed as part of a separate issue that was fixed this year, https://github.com/whosonfirst-data/whosonfirst-data/issues/538 (PR: https://github.com/whosonfirst-data/whosonfirst-data-admin-us/pull/86)

I'll close this issue, but feel free to re-open if there are more fixes needed to the new Fairfield record.
