### ISSUE TITLE
How often is the sqlite inventory updated?

### ISSUE THREAD

**Issue by hereticaneue** [whosonfirst-data/whosonfirst-data#1464]
I realize this depends on how much the actual data has been updated, but I'm wondering if there's any sort of plan/schedule. Like "we try to push updates twice a year" or if it's more like "whenever we get around to it." I'm trying to figure out how often I should think about downloading and ingesting the updates on my end, so knowing when updates happen would be helpful. 

(And I'm mostly interested in venues, but since they're spread out over many repos, I thought asking in this one would be prudent -- hope that's ok!)

Thanks!

**Comment by stepps00** [comment]
Hi @hereticaneue - the various sqlite distribution files ([here](https://dist.whosonfirst.org/sqlite/)) are updated whenever a change is made to the Who's On First records in the relevant repo(s). 

Since these distribution files are generated automatically, we don't have regularly scheduled pushes. Grabbing the "latest" distribution should give you the most recent records for that given placetype/repo. Hope that helps!

**Comment by nvkelso** [comment]
@hereticaneue Nice avatar. What @stepps00 said: generally the admin placetypes get updated daily on an as-needed / as the data changes basis. The `venues` repos have very little activity month to month, so probably for a build or quarterly would be fine for you using those venue dists.

**Comment by hereticaneue** [comment]
Excellent - thank you both for your quick and thorough answers!
