### ISSUE TITLE
localadmin missing src:lbl property

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#153]
https://github.com/whosonfirst/whosonfirst-data/blob/dad5fc709a7290b9d6b3206fa670a530283b7736/data/404/518/459/404518459.geojson

Has the label latitude, longitude set, but doesn't say where it's from. 

This also seems to be causing the Spelunker to not display the label point (and erroring out with Oh Noes!!! https://whosonfirst.mapzen.com/spelunker/id/404518459/).

**Comment by stepps00** [comment]
Looking through the [Git history](https://github.com/whosonfirst-data/whosonfirst-data/commits/master/data/404/518/459/404518459.geojson) of this feature, it looks like [this commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/340f91d1fde0bbd2e5449dd9b58646186901f5da) fixed the problem of missing `"src:lbl:centroid"` properties. 

@nvkelso - this issue seems to be fixed. Are we comfortable closing this issue?

**Comment by nvkelso** [comment]
Yep :)
