### ISSUE TITLE
Remap whosonfirst-data to per-country repos

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#1594]
Since introducing per-country repositories, a half dozen PRs have been merged into this repository.

Let's use this issue to track re-mapping and pushing these merged changes into the pre-country repos. Eventually, it may also be helpful to place country-specific issues into the per-country repositories.

**Comment by nvkelso** [comment]
(Let’s continue using a single issue tracker instead of moving issues.)

**Comment by missinglink** [comment]
Hi guys, are you intending on doing some sort of public announcement of the repo changes?

I'm assuming for now that the `sqlite` and `bundle` distributions are doing to remain backwards compatible, with planet-wide distributions continuing to be updated?

We'd like to add per-country support in Pelias at some point, so users who don't want to download the whole planet when they only need a few thousand records.

This might also open up some opportunities for better external collaboration, in the past, it's been difficult & unwieldy to contribute to the project because of the size of the `whosonfirst-data` repo and having to set up all the tooling (be it Python or Go).

Regarding the single issue tracker, that makes total sense, but I'm guessing the PRs would go against the individual repos?

**Comment by nvkelso** [comment]
Hi @missinglink! This is still a WIP, but we expect the work to complete in May – please expect an announcement next month. 

Yes, the sqlite and bundle distributions should remain backwards compatible. I like your idea to add per country download options. Yes, the PRs would be against individual repos.

**Comment by stepps00** [comment]
This is ongoing; commits are being added to the per-country repos right now that will bring each per-country repo up to speed with this repo. Once complete, we can focus edits in the per-country repos.

**Comment by stepps00** [comment]
Work to update distribution files is ongoing, but this work is complete. Admin data now lives in per-country repos.

A bit more about that work here: https://whosonfirst.org/blog/2019/05/09/changes/.

**Comment by missinglink** [comment]
Nice work!

I just realised that I opened issues on the -xy repo when I guess I should have opened them against this one?

@nvkelso suggested that WOF uses a single issue tracker going forward, if that's the case I'd suggest disabling the `Issues` functionality for the other repos before you get too many issues opened there and it gets out of hand?

**Comment by stepps00** [comment]
Good point.. the idea going forward is to have a single repository to track issues, with README files in the per-country repositories pointing to that issue tracking repository. We should disable Issues functionality as part of that work.
