### ISSUE TITLE
Berlin kiez have incorrect localadmin

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1652]
The record [420784283](https://spatial.synergy.io/explore/place/wof/420784283) shows a `localadmin_id` of [1377683779](https://spatial.synergy.io/demo/place/wof/1377683779).

This is not correct, it seems to have been introduced in https://github.com/whosonfirst-data/whosonfirst-data-admin-de/commit/0884b5d0899dbc15a55a55665aa87272ae9138ad

I'll check a few more, hopefully it's a one-off

**Comment by missinglink** [comment]
hmm same for https://spatial.synergy.io/demo/place/wof/420784259

I wonder if there is something odd about `1377683779` which is causing it to PIP to these geometries which appear to be disjoint?

**Comment by missinglink** [comment]
Neither of those two 'kiez' I linked is associated to Berlin, so something is definitely amiss?

**Comment by stepps00** [comment]
Hmmm, that is strange.. I thought this was due to a funky join in the recent Germany work, but that doesn't look to be the case. The PR was run against PIP tools, but the hierarchies of these examples do not look correct.

Re-PIPing Germany admin records should fix this issue. I'll push PIP changes to a new branch and flag this issue once complete.

**Comment by missinglink** [comment]
Hmm yea odd, I thought it might be the reverse geo point but that seems fine 🤷‍♂ 
https://gist.github.com/missinglink/c9bd2c74d37fe6228cb8a1a6219e69c2

**Comment by missinglink** [comment]
There are other weird associations such as [Berlin](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-de/master/data/101/909/779/101909779.geojson) being parented by [Potsdam-Mittelmark](https://spatial.synergy.io/demo/place/wof/102063937) which is also incorrect.

**Comment by missinglink** [comment]
I just noticed today that the `lbl` position lies outside the Berlin polygon, could this be the reason?
https://spatial.synergy.io/explore/place/wof/101909779

**Comment by stepps00** [comment]
Good catch - that is the cause of this issue.

By updating the lat/long values in the Berlin record, I should be able to re-PIP the record to update all descendant hierarchies; I'll file a PR.

While I'm at it, it would be worthwhile to check if other polygon geometries have lbl positions that fall outside of the polygon extent and update those as well.

**Comment by missinglink** [comment]
@stepps00 I ran a spatial query today to generate a list of `lbl` and `reversegeo` points which are not contained by their parent geometry.

unfortunately, I found 5200 occurrences (based on a recent copy of sqlite databases), the full list is here:
https://gist.github.com/missinglink/eb49b8354226329d3e6bc0cbc34aaee3

I spot-checked a few of them on `spatial.synergy.io` and the list seems to be correct.
Sounds like a lot of work ;(

Let me know if I can help with a programmatic fix, I could, for instance, check the `mps` positions too and see if they are better, or I can provide the 'mathsy centroid' values you see in the blue markers.

**Comment by stepps00** [comment]
Thanks for the list! 5200 records is not ideal, but somewhat expected given the amount of records in WOF. 

In addition to the lbl:* and mps:* properties, there are also [reversegeo:*](https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/reversegeo) properties, which are used as the first-choice lat/long when PIP-ing records.

By running these 5200 records against Mapshaper to gain new inner centroids, my hope is that we can apply those values to the reversegeo:* properties and fix the hierarchies in these records through a re-PIP.

I'd prefer adding reversegeo:* properties, rather than updating label positions since some (many?) of those label positions were hand-curated.

**Comment by missinglink** [comment]
Proposing a simple fix for the Berlin issue https://github.com/whosonfirst-data/whosonfirst-data-admin-de/pull/9.
Will require re-PIP-ing related records to rewrite the `wof:hierarchy` for places such as https://spatial.synergy.io/explore/place/wof/420784283.
