### ISSUE TITLE
Fix Stair, Trabboch, Scotland, UK

### ISSUE THREAD

**Issue by tomtaylor** [whosonfirst-data/whosonfirst-data#1670]
https://spelunker.whosonfirst.org/id/1276363679/

ID 1276363679 is named 'Stair, Trabboch', but these are two separate places, 2 miles apart, and should be separated.

Additionally, it has multiple hierarchies, belonging to both Argyll and Bute and East Ayrshire. Local knowledge tells me the correct localadmin should be East Ayrshire (404451413).

**Comment by stepps00** [comment]
Thanks @tomtaylor - Agreed that this record should be deprcated and split into the appropriate records for "Stair" and "Trabboch". It also looks like the hierarchy needs a bit of work here - one of the hierarchies is invalid.

If you notice additional issues, feel free to append them here. Otherwise, we'll update shortly.

**Comment by tomtaylor** [comment]
@stepps00 thanks!
