### ISSUE TITLE
Update geometry for Waiheke Island

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#1691]
I'd like to replace the existing geometry https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/blob/master/data/101/916/761/101916761.geojson

... with this one https://gist.github.com/missinglink/cac3c4dcee35b1e1514e4d3c58b46565

I sourced it via https://datafinder.stats.govt.nz/layer/27771-area-unit-2017-generalised-version/

The License is `Creative Commons Attribution 3.0 New Zealand`

**Comment by missinglink** [comment]
I could try and handle this one myself @stepps00, I think I have a handle on editing the geometry and I'll run it through exportify too.

One thing I'm not too confident about is that I guess I'll need to add a new source to `whosonfirst-sources` right?

**Comment by stepps00** [comment]
Thanks @missinglink..

As for the source, yes, we'd need to add a new source file in [`whosonfirst-sources'](https://github.com/whosonfirst/whosonfirst-sources#adding-a-new-source). Take a shot at that and let me know if you run into any issues.

As for the geometry update, I'm not sure the new geometry (entire island) actually represents a locality. What I think needs to happen here:

- The locality records on Waiheke Island need to be updated with better geometries.. there are several localities that comprise the island, which include Surfdale, Oneroa, and Palm Beach. WOF has some, and some are missing. Examples:
  - https://spelunker.whosonfirst.org/id/101916773/
  - https://spelunker.whosonfirst.org/id/101915353/
  - https://spelunker.whosonfirst.org/id/1126020877/
- [101916761](https://spelunker.whosonfirst.org/id/101916761/) needs to be deprecated and marked as not current. This geometry seems to be a portion of Surfdale and not the entire island (I assume this was named from a bunk spatial join at some point).

It could also be argued that places like Surfdale, Oneroa, and Palm Beach could be put at the `neighbourhood` placetype rather than the `locality` placetype, but I wouldn't know that without looking at all placetype coverage in WOF. Either way, updating that single record with the entire island's geometry would cause issues with overlapping other localities, so we unfortunately we can't simply update that locality geometry.

I'd like to spend more time updating locality geometries like we've done in [Switzerland](https://github.com/whosonfirst-data/whosonfirst-data/issues/1334), let's chat about a larger update..

**Comment by missinglink** [comment]
This issue will be resolved by https://github.com/whosonfirst-data/whosonfirst-data/issues/1878

See https://github.com/whosonfirst-data/whosonfirst-data/issues/1878#issuecomment-674811266

**Comment by stepps00** [comment]
This has been taken care of via https://github.com/whosonfirst-data/whosonfirst-data-admin-nz/pull/12. We've adjusted all locality placetype records on Waiheke Island and created a new localadmin record for the entirety of Waiheke Island.

Localadmin shown with a darker boundary (entire island), localities shown with a thin blue boundary:

<img width="1191" alt="Screen Shot 2020-10-20 at 10 22 51 AM" src="https://user-images.githubusercontent.com/18567700/96622208-7e7adf00-12be-11eb-989c-0d54a64a0f1a.png">
