### ISSUE TITLE
Problems with names on Brazilian Counties 

### ISSUE THREAD

**Issue by leandro-lugaresi** [whosonfirst-data/whosonfirst-data#1756]
Our company is trying to import and use the Brazilian counties, we started to verify the registries on the state of São Paulo and see some issues (a lot of them) with the names. For me appears to be an encoding conversion problem. 
I got the counties from the sqlite exported databases using this query:
```sql
SELECT
coalesce(
json_extract(body, '$.properties.name:por_x_preferred[0]'),
json_extract(body, '$.properties.name:und_x_variant[0]'),
spr.name) AS name
  FROM spr
  INNER JOIN geojson on (geojson.id = spr.id)
 where spr.parent_id = 85682041 and spr.placetype = "county" and spr.is_current != 0 order by name asc

```
To compare, I got the São Paulo counties to compare from Wikipedia: [Lista de municipios de São Paulo](https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_de_S%C3%A3o_Paulo_por_popula%C3%A7%C3%A3o)

Here is the diff from the two lists: [diff](https://www.diffchecker.com/ekB4l35W)

As I can see, the portuguese names are with some wrong accentuation, some examples:

ID | name | pt-br name
------------ | -------------| ----------
[102060993](https://spelunker.whosonfirst.org/id/102060993/) | AGUAÃ | Aguaí
[102061019](https://spelunker.whosonfirst.org/id/102061019/) | ALUMÃNIO | Alumínio
[102061031](https://spelunker.whosonfirst.org/id/102061031/) | AMÃRICO BRASILIENSE | Américo Brasiliense

Can we update these values for Portuguese? I can work to create a PR with the correct pt-br names.

**Comment by stepps00** [comment]
Hey @leandro-lugaresi - more than happy to work with you to update the names of county records in Brazil.

The existing `wof:name`, `name:eng_x_preferred`, and `label:eng_x_preferred_longname` values for Brazil counties look correct at first glance, but the issue is that:

- the `label:por_x_preferred_longname` names are stripped of accent marks
- `name:por_x_preferred` names are missing

The `name:und_x_variant` names represent "undefined" language translations - essentially a bucket of names that we get from sources (in this case Quattroshapes) that don't belong in another language list. So with these, they're fine to stay in the existing `und` variant list.

If you were able to create a `wof:id` <> Portuguese name translation mapping, I could easily import these new names/labels in each WOF county record. Would that work?

Something like:

wof:id | por_name
--|--
102060993 | Aguaí
102061019 | Alumínio
102061031 | Américo Brasiliense

If you're able to provide a CSV file with `wof:id` values of each county in Brazil, I could craft a PR with all needed changes fairly quickly.

**Comment by leandro-lugaresi** [comment]
Hey!
I finished the script and the clean process for this update for all counties in Brazil.
## Process
First I downloaded the IBGE xls with all the counties in Brazil version 2018 [here](ftp://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/divisao_territorial/2018/).
After that, I create a wof CSV file containing the wof ID and the portuguese name using these query:
```sql
SELECT
inn.id,
inn.name,
out.name AS state
  FROM spr inn
  INNER JOIN spr out on (inn.parent_id = out.id)
 where inn.placetype = "county" and inn.is_current != 0 order by state, inn.name asc
```

Then I created a script in go to generate the CSV with the closest string inside the region.
If the difference is greater than 3 I logged and analyzed every case separated.
## Problems
1: https://spelunker.whosonfirst.org/id/102058763/
The name change to `Serra Caiada`: https://pt.wikipedia.org/wiki/Serra_Caiada

2: https://spelunker.whosonfirst.org/id/102056375/
The old name was Santarém but changed in 2010 to `Joca Claudino`: https://pt.wikipedia.org/wiki/Joca_Claudino

3: https://spelunker.whosonfirst.org/id/102058433/
The name has a typo BUT the problem was because of the wrong parent_id. The correct parent_id should be https://spelunker.whosonfirst.org/id/85681991/

**Comment by stepps00** [comment]
This is great, thanks @leandro-lugaresi!

To reiterate, it looks like we need to do the following to WOF records:

- Use the id <> name mapping that you provided to update (or add new) `name:por_x_preferred` and 'label:por_x_preferred_longname` properties
- Update hierarchies of all `county` records in Brazil, as well as descendant records to address issues with parenting, as seen in https://spelunker.whosonfirst.org/id/102058433/

The only caveat being your problem #2 above. Are there additional county records that have had name changes? I want to make sure we catalogue the historical names of these places.

I'll use this mapping to update records in a PR and link here - thanks again.

**Comment by stepps00** [comment]
Looks like three records have new names:

-  https://spelunker.whosonfirst.org/id/102056375
-  https://spelunker.whosonfirst.org/id/102058763
-  https://spelunker.whosonfirst.org/id/102056433
