### ISSUE TITLE
Upgrade neighbourhoods in Buenos Aires

### ISSUE THREAD

**Issue by meetar** [whosonfirst-data/whosonfirst-data#180]
According to our resident expert in Buenos Aires neighborhood topology, this neighborhood should only have the southernmost shape, and the other two polygons may belong to another neighborhood – or maybe the people who caused the northern areas to be included in this neighborhood were lost, and this may be a cry for help:

https://github.com/whosonfirst/whosonfirst-data/blob/master/data/857/643/11/85764311.geojson

______________________
_(stepps00: edited 02-02-2017)_

### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Upgrade** locality record's shape
- [x] **Draft review**
- [ ] **Draft revisions** based on review comments
- [ ] **Final review**
- [ ] **Final revisions** based on review comments
- [ ] **Import** into Who's On First

### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
See also: https://whosonfirst.mapzen.com/spelunker/id/85764311/

<img width="1184" alt="screen shot 2015-12-16 at 14 33 55" src="https://cloud.githubusercontent.com/assets/853051/11855928/188840dc-a402-11e5-8d4f-d5f26e826d5f.png">

**Comment by stepps00** [comment]
Pulled all neighbourhood records in Buenos Aires, the same issue is occurring with the following records:

https://whosonfirst.mapzen.com/spelunker/id/85764025
https://whosonfirst.mapzen.com/spelunker/id/85764079
https://whosonfirst.mapzen.com/spelunker/id/85764109
https://whosonfirst.mapzen.com/spelunker/id/85764113
https://whosonfirst.mapzen.com/spelunker/id/85764129
https://whosonfirst.mapzen.com/spelunker/id/85764135
https://whosonfirst.mapzen.com/spelunker/id/85764183
https://whosonfirst.mapzen.com/spelunker/id/85764185
https://whosonfirst.mapzen.com/spelunker/id/85764225
https://whosonfirst.mapzen.com/spelunker/id/85764227
https://whosonfirst.mapzen.com/spelunker/id/85764235
https://whosonfirst.mapzen.com/spelunker/id/85764259
https://whosonfirst.mapzen.com/spelunker/id/85764271
https://whosonfirst.mapzen.com/spelunker/id/85764281
https://whosonfirst.mapzen.com/spelunker/id/85764311 (original)
https://whosonfirst.mapzen.com/spelunker/id/85764325
https://whosonfirst.mapzen.com/spelunker/id/85764329
https://whosonfirst.mapzen.com/spelunker/id/85764333

**Comment by stepps00** [comment]
I've updated this issue to match other neighbourhood update issues in this repo. Our neighbourhood workflow and tools should fix this problem (and all erroneous neighbourhoods in Buenos Aires).

**Comment by mfogel** [comment]
Of note: the neighborhoods in Buenos Aires are defined precisely by the government: http://www.buenosaires.gob.ar/laciudad/barrios

OpenStreetMap appears to have good traces of these neighborhoods already in their database.

**Comment by stepps00** [comment]
Thanks @mfogel! We will investigate that source for any data available under a CC-BY, CC0 or equivalent license and update our records with the defined boundaries!

**Comment by mfogel** [comment]
@stepps00 no prob, happy to help. Hopefully I beat you to the punch and didn't just do duplicate work, but in any case - I did some more investigation:

BA has an 'open data' portal, and makes neighborhood polygon data available for download as a series of coordinates: https://data.buenosaires.gob.ar/dataset/barrios

The data on there appears to be licensed via a 'cc-by' with no 'share alike' terms. The exact conditions for re-use of their data are listed under "III. Política de reutilización de datos abiertos. Condiciones" here https://data.buenosaires.gob.ar/tyc It's in spanish obviously but here's what google translate gives for that section:

> Do not denature the meaning of information.
> 1. Reference should be made to the source of the documents to be reused. This appointment may be made as follows: "SOURCE: Government of the Autonomous City of Buenos Aires
> 1. The date of the last update of the documents subject to reuse must be mentioned.
> 1. The Government of the City of Buenos Aires may not indicate, imply or suggest that it participates, sponsors or supports the use or reuse of it.
> 1. The metadata on the date of updating and the applicable re-use conditions, including, where appropriate, the document made available for use or re-use must be preserved, and therefore not altered or deleted.

If those license terms are acceptable to WOF, I'd be willing to use their downloads to prepare a PR with updates to the geojson files for the BA neighborhoods. Let me know what you think.

Cheers.

**Comment by stepps00** [comment]
Hey @mfogel - I read through the open data license on the  https://data.buenosaires.gob.ar/tyc site and it looks like the data allows Who's On First to use the data through a `CC BY` equivalent license.. good news!

I have not updated any Who's On First records or imported any data via the Open Data portal - we'd be more than happy to work with you to import these new features through a PR.

Because we already have records in Buenos Aires at the `neighbourhood` placetype, we're going to need to replace and update existing Who's On First records, as well as import new records. We've written a "how-to" guide on updating neighbourhood records [here](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/issue_workflows/sf_neighbourhood_updates_pt_1.md). 

We're developing a more streamlined process to update neighbourhood records, but if you're open to filing a PR, feel free to update records and we'll go over any updates that are made. Thanks for the information and feel free to let us know if you have any questions!

**Comment by mfogel** [comment]
I've started a branch with updated neighborhoods for BA here: https://github.com/mfogel/whosonfirst-data/tree/buenos-aires-neighborhoods

@stepps00 should I be keeping the old quattroshapes geometries around as an 'alternate' geometry? My 0.02 would be to not bother... they're pretty bad. Ex [fixed](https://github.com/mfogel/whosonfirst-data/blob/buenos-aires-neighborhoods/data/857/640/99/85764099.geojson) vs. [quattroshapes](https://github.com/mfogel/whosonfirst-data/blob/master/data/857/640/99/85764099.geojson). But I can set them up as alternate geometries if you think that's best.

**Comment by nvkelso** [comment]
Even though they can be funky, they are a primary source and our workflow is to preserve quattroshape neighbourhood geometries as alts.

**Comment by stepps00** [comment]
@mfogel - Echoing what @nvkelso said.. yes, we need to preserve those geometries as alt-geometries. They may be outdated and/or oversized, but ideally we'd like to preserve as much about each "place" as possible.

**Comment by mfogel** [comment]
@stepps00 (or @nvkelso) would like your thoughts on whether Comunas should be classified as 'counties' or 'boroughs' in the WOF structure:

In the real world:

 * officially, the city of BA is neither a province nor within a province. It's a city without a province. However, it operates much the same as a province (elects representatives to the federal gov, has 'legislature' rather than a 'city council', etc) 
 * the Comunas are administrative districts within the city. There are 15 of them. Each Comuna wholly contains between 1 and 6 neighborhoods.
 * there are 48 neighborhoods defined in the city.

Representing this in WOF is a little tricky, as 'region' and 'locality' both appear to be required in the hierarchy above 'neighborhood'. So I can see two ways:

 * Region (1) -> Locality (1) -> Boroughs (15) -> Neighborhoods (48).

or 

 * Region (1) -> Counties (15) -> Locality (1) -> Neighborhoods (48)

In both structures I would make the region and locality records coterminous, as they both represent the same thing - the city of BA.

The second structure has a few disadvantages that I can see:

 * the Locality record should contain 15 separate hierarchies, one for each county, correct? At least this is how NYC is currently set up for its coverage of 5 counties. Seems like a lot of overhead, especially when in reality the city does not report to the Comunas... it's the other way around.
 * the neighborhood parent_id pointers would go straight to the locality record, whereas it would probably be better if they went to the record for the Comuna that contains them.

Currently, the hierarchy is set up in the 2nd structure, but it appears to me it would be better in the 1st. If you all are on board, I'd like to change the hierarchy from the 2nd structure to the 1st... 

Thoughts? Thanks.

**Comment by stepps00** [comment]
Hey @mfogel - thanks for the write-up!

This same case pops up in other localities around the world and can be tricky when updating WOF records. Both of your suggestions are valid workflows for dealing with the placetypes in the `region`, but because "the Comunas are administrative districts within the city" and communas report to the locality of Buenos Aires, I would default to the following:

Region (1) -> Locality (1) -> Boroughs (15) -> Neighborhoods (48).

Additionally, setting the `wof:coterminous` property for the `region` and `locality` is the right thing to do in this case.

Otherwise, you are correct - a multiple hierarchy would need to be built for Buenos Aires, similar to how we've setup New York City.

cc @nvkelso.

**Comment by nvkelso** [comment]
Using `borough` makes sense to me here for the "comunas" in BA.

Those also sound like `localadmin` a bit, so when we import "comunas" them outside BA we could give the BA instances imported here a `"wof:placetype_alt":"localadmin"` to not double import, but future future.

**Comment by mfogel** [comment]
Re: comunas & boroughs & counties - sounds good.

One (hopefully) last question:

The `wof:geomhash` property... could you point me at some example code where that's calculated? I see in the [docs](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#geomhash) that I probably don't have to worry about it but I'm curious all the same. I see some references to it in the `whosonfirst/whosonfirst-www-boundaryissues` repo but I haven't been able to track down how it's calculated.

Thanks

**Comment by stepps00** [comment]
Hey @mfogel - the `wof:geomhash` property is something that is generally calculated upon import, so it is not a property that we expect anyone to calculate when updating neighbourhood records.

Either way, the geomhash is calculated through one of our utility scripts, specifically [here](https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/mapzen/whosonfirst/utils/__init__.py#L60-L72). Additional information of the hashlib module can be found [here](https://docs.python.org/2/library/hashlib.html).

**Comment by mfogel** [comment]
For some reason my hashes aren't matching what's in WOF for existing records. Not going to worry about it ATM. I've set `wof:geomhash` to the empty string for records which I updated the geometry. Thanks for the info though.

As referenced above, I've opened two pull requests - one for the new source and one for the data from the new source. Let me know if you'd like to see tweaks - or if you'd just like to make them yourself please feel free, I've given you all push access to the branches.

**Comment by stepps00** [comment]
@mfogel - thanks! I will take a look at the two PRs and let you know if I have any questions.
