### ISSUE TITLE
Missing properties.src:alt_label properties

### ISSUE THREAD

**Issue by laszbalo** [whosonfirst-data/whosonfirst-data#1804]
Hi,

a couple of days ago I was pointed to [this](https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/creating_alt_geometries.md#what-rules-must-alt-geometries-follow) doc which lists the required and optional properties of the alt file. I am assuming that the linked doc has not been updated yet with the new `properties.src:alt_label` property, right?

So far I have found the following alt records without the `alt_label` field:

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-de/master/data/101/905/681/10190568-alt-quattroshapes.geojson

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-ca/master/data/101/736/983/101736983-alt-quattroshapes-reversegeo.geojson

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-pl/master/data/856/337/23/8563372-alt-quattroshapes.geojson

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-th/master/data/102/025/001/102025001-alt-quattroshapes_pg.geojson

https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-tv/master/data/856/326/07/85632607-alt-naturalearth-display-terrestrial-zoom6.geojson

**Comment by stepps00** [comment]
Hey @laszbalo - thanks for the issue. I will file an issue in the `whosonfirst-cookbook` repo to update that doc because it is out of date.. I'll need to add a blurb about `src:alt_label`.

I am actually in the process of crawling the WOF admin repos as a part of https://github.com/whosonfirst-data/whosonfirst-data/issues/1793, so I'll include a check/update for this issue as part of that crawl work.

Let me circle back to this issue once I start merging commits for #1793.

**Comment by stepps00** [comment]
I'm tackling this issue in parallel with https://github.com/whosonfirst-data/whosonfirst-data/issues/1729.

Affected repos include:
- whosonfirst-data-admin-tv
- whosonfirst-data-admin-pl
- whosonfirst-data-admin-de
- whosonfirst-data-admin-ca
- whosonfirst-data-admin-me
- whosonfirst-data-admin-ch

**Comment by stepps00** [comment]
This is complete, closing.
