### ISSUE TITLE
shapefile build

### ISSUE THREAD

**Issue by justinelliotmeyers** [whosonfirst-data/whosonfirst-data#1820]
Is there anyway someone can code out a annual/ bi-annual/ quarterly/ etc shapefile build of all the data? The directory folder structure is a nightmare for people who try to grab this stuff in a boomer fashion (*me). Id love to see what is in here, but honestly dont try because I cannot figure out what is where and how to put it together. 

Might have a call w @stepps00 this week. Any thoughts @nvkelso ?  Thanks and hope you guys are having fun in QUARANTINE!

**Comment by thisisaaronland** [comment]
@justinelliotmeyers It's been on the list for a long time but everyone's various Other Commitments get in the way.

There is early work to generate Shapefiles here:

https://github.com/whosonfirst/go-whosonfirst-shapefile

The immediate challenge for shapefiles is that WOF data does not adhere to a uniform shape type which is necessary for shapefiles. The code above could be refactored easily enough to generate multiple shapefiles (one per placetype) but "time and typing" and all that.

**Comment by justinelliotmeyers** [comment]
since shapefile is honestly the worst filetype... is there a way to do it, but keep it simple? ie just an id field and then a joinable csv so it can pull in esri software then brought in a fgdb? or even in qgis, just bring in by region, the subset and join a table?

**Comment by missinglink** [comment]
Hey Justin, this is probably fairly simple with the right `ogr2ogr` command.

If you don't have any luck hit me up on email.

**Comment by missinglink** [comment]
hmm I had a quick crack at this and it seems you're correct in saying that Shapefiles suck, lots of these errors:

```
Warning 6: Normalized/laundered field name: 'name:dan_x_variant' to 'name_dan_x'
ERROR 6: Can't create fields of type StringList on shapefile layers.
Warning 1: The output driver does not natively support StringList type for field name:est_x_variant. Misconversion can happen. -mapFieldType can be used to control field type conversion.
```

**Comment by missinglink** [comment]
```
#!/bin/bash

HOST='https://data.geocode.earth/wof/dist/sqlite'
DIST='whosonfirst-data-admin-us-latest'

if [ ! -f "${DIST}.db" ]; then
  echo 'downloading data'
  echo 'depends on: curl, lbunzip2'
  curl -s "${HOST}/${DIST}.db.bz2" | lbunzip2 > "${DIST}.db"
fi

if [ ! -f "${DIST}.polygon.shp" ]; then
  echo 'generate polygon database'
  echo 'depends on: sqlite3, ogr2ogr'
  cat <<SQL | sqlite3 "${DIST}.db" | ogr2ogr -skipfailures -f 'ESRI Shapefile' "${DIST}.polygon.shp" /vsistdin/
    SELECT body
    FROM geojson
    WHERE UPPER(json_extract(body, '$.geometry.type')) == 'POLYGON';
SQL
fi
```

**Comment by missinglink** [comment]
Geocode Earth has three formats available here https://geocode.earth/data/whosonfirst, the third one is spatialite but unfortunately wont render in QGIS because it uses the `GEOMETRY` data type which isn't supported by QGISS yet!

If you'd just like to have a look around, check out https://spatial.demo.geocode.earth/explore/pip on a desktop machine and pan around the map a bit.

**Comment by thisisaaronland** [comment]
In the short-term you may want to use the `wof-csv-to-feature-collection` tool which can be converted to a shapefile using `ogr2ogr` as @missinglink suggests:

https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/scripts/wof-csv-to-feature-collection

This has been the workflow in the past for editing geometries.  @stepps00 can fill you in on the details.

**Comment by missinglink** [comment]
Looks like you can load directly into QGIS from a directory clone, eg for New Zealand:

https://github.com/whosonfirst-data/whosonfirst-data-admin-nz

```
git clone https://github.com/whosonfirst-data/whosonfirst-data-admin-nz.git
```

<img width="876" alt="Screenshot 2020-04-06 at 21 00 40" src="https://user-images.githubusercontent.com/738069/78595519-6b388280-784a-11ea-89c9-1911e882adab.png">
<img width="470" alt="Screenshot 2020-04-06 at 21 01 33" src="https://user-images.githubusercontent.com/738069/78595526-6d9adc80-784a-11ea-8649-312c96bd9da5.png">
<img width="312" alt="Screenshot 2020-04-06 at 21 02 31" src="https://user-images.githubusercontent.com/738069/78595528-6d9adc80-784a-11ea-8e08-b549a84d7716.png">

There's a lot of data so it'll take a while to load...

**Comment by thisisaaronland** [comment]
@missinglink That would make a good blog post: https://github.com/whosonfirst/whosonfirst-www/tree/master/www/blog

**Comment by missinglink** [comment]
I'm not sure if I can really advocate this method, it took a really long time (like I watched a Netflix episode long time) to load NZ and makes GQIS effectively unresponsive due to the amount of data.

@justinelliotmeyers how do you usually deal with very large datasets like this in QGIS?

**Comment by missinglink** [comment]
<img width="405" alt="Screenshot 2020-04-06 at 21 58 51" src="https://user-images.githubusercontent.com/738069/78599678-db96d200-7851-11ea-9a5c-3b334dba0902.png">

**Comment by missinglink** [comment]
Hey, so I think having several 20GB shapefiles isn't really a great solution for GIS people accessing the data :(

Distributing the data as one very large file is problematic because loading it all into a GUI app is pretty much a non-starter due to the amount of features present.

Distributing it as many small files (like it is now) is probably superior in that regard, the problem of loading a directory recursively can be solved with a plugin like I showed above when the GUI software doesn't natively support it.

I'd suggest changing the title of this issue to something that describes the problem rather than jumping to a proposed solution (ie. shapefiles), maybe we can close this and start a discussion?

I guess what would be most useful is for people like Justin is to be able to pick and choose a 'medium sized' chunk of the data based on some filter conditions and just load that, it's not the easiest discovery mechanism but it helps mitigate the scale issues.

In order to accomplish that there needs to be some sort of index which can be queried in order to establish a set of filter conditions before the main import is done.

I'm not familiar enough with GIS software to comment on what would be best (and universal).

The `spr` table of the `sqlite` distributions contains most of the information anyone would like to have in such an index, but how to make that work in QGIS?

**Comment by missinglink** [comment]
The `.dbf` file of shapefiles actually probably makes this much easier, I'm assuming that QGIS is able to load this first and then based on the filter conditions it selectively loads the geometries from the `.shp` file?

One issue with conversion is that the WOF properties are nested and sometimes non-string values such as arrays which would make conversion lossy ;(

**Comment by justinelliotmeyers** [comment]
@missinglink and @thisisaaronland  thanks for looking into this for me. If files grow that big that quick, then wof cant be converted to shapefile globally unless someone has tons of space for processing/ extracting/ using. after 2gb the shapefile is corrupt anyway. I'll just have to learn the dir structure of the geojsons and extract what i need from the data.

The WOF data and project are amazing, but for me it's impossible to extract and use, but maybe i need to tinker more before I just give up. Whats the best way to use the data and visualize all of the layers/ placetypes for a specific country or globally?

I can close this ticket out if you are both okay with that?  Really appreciate all of your time and help trying to assist. 

Justin

**Comment by thisisaaronland** [comment]
The `wof-csv-to-feature-collection` was designed to produce (n) GeoJSON files specifically to account for the 2GB limit in shapefiles.

It's probably not much consolation but the motivation and the design of the layout (a bazillion tiny files) was specifically to prevent the data from getting painted in to any one vendor/database corner.

At the end of the day it's just a lot of data. The world is a big place so there's not much to be done about that. There are definitely gaps in the tooling/availability/resourcing for canned distributions and in particular canned-and-themed distributions.

One early approach was to bundle "meta" (CSV) files with repos such that you could do easy/quick filtering on a manageable dataset (a few millions rows rather than full GeoJSON records) and fetch the actual data post-query. We eventually moved the meta files out of the repos because they became burdensome but it might be worth revisiting producing and publishing the meta files.

There was never a formal captial-S spec for meta files but this is what gets published:

https://github.com/whosonfirst/py-mapzen-whosonfirst-meta/blob/master/mapzen/whosonfirst/meta/__init__.py#L78-L105

Independent of other issues it would be useful to know whether you'd want additional properties to be able to filter on.

**Comment by stepps00** [comment]
> Whats the best way to use the data and visualize all of the layers/ placetypes for a specific country or globally?

While the "Load Them All" tool in QGIS is helpful, it doesn't handle directories with more than a few thousand GeoJSON files well. It works fine if you're handling a small repo like the [whosonfirst-data-admin-tv](https://github.com/whosonfirst-data/whosonfirst-data-admin-tv) (Tuvalu) repo, but isn't able to handle a large repo like the US, Canada, or India.

As @thisisaaronland mentioned, the [csv-to-feature-collection](https://github.com/whosonfirst/py-mapzen-whosonfirst-utils/blob/master/scripts/wof-csv-to-feature-collection) script can be used to grab X records from a repository. The tool exports a GeoJSON feature collection that you can then pass through Mapshaper to [simplify](https://github.com/mbloch/mapshaper/wiki/Command-Reference#-simplify) the file, then easily load into QGIS. I've found that this helps visualize coverage per placetype/country.

@justinelliotmeyers - happy to work with you to help you export what you're interested in. Alternatively, the sqlite distributions mentioned above are another option.

**Comment by nvkelso** [comment]
This has come up a few times and would be generally useful, reopening.

**Comment by thisisaaronland** [comment]
Okay, at the risk of "painting the bikeshed" this feels like as good an opportunity as any to reconsider/refactor/retire the `go-whosonfirst-index` packages which have grown in to a confusing mix of code to iterate over an arbitrary set of WOF records as well as indexing/ingesting/publishing them.

You don't need to look further than the dependency chain for the `go-whosonfirst-sqlite` package:

https://github.com/whosonfirst/go-whosonfirst-sqlite#dependencies-and-relationships

Independent of shapefile work it's been on my list / turning around in my head to create a new set of `go-whosonfirst-crawl` packages whose only goal is to iterate over a set of WOF records with minimal (possibly extensible) filtering and emit matches.

That would also create space to update the `-index` packages or replace them entirely with `go-whosonfirst-publish` packages that ingest atomic records (rather than lists or sets) according to their own heuristics. That could include multiple output targets like by placetype or, in the case of shapefiles, by geometry type.

It's still early days in my thinking but it seems evident that the existing `-index` packages are showing their limits.

**Comment by thisisaaronland** [comment]
Work in progress: https://github.com/whosonfirst/go-whosonfirst-iterate

**Comment by missinglink** [comment]
The following steps can be used to convert a WOF repo to `GeoPackage` format, which can then be loaded into `QGIS`:

```bash
# SELECT A COUNTRY CODE
COUNTRY_CODE='nz'

# PERFORM A BARE CLONE OF THE REPO
# note: a regular clone is also usable here but this saves disk space
git clone \
  --bare \
  --depth 1 \
  --single-branch \
  --branch master \
  https://github.com/whosonfirst-data/whosonfirst-data-admin-${COUNTRY_CODE}.git ${COUNTRY_CODE}

# OUTPUT THE GEOJSON
# note: one per line minified and gzipped to save disk
git --git-dir=${COUNTRY_CODE} archive HEAD data \
  | bsdtar -xOf - --include '*.geojson' \
  | jq -c . \
  | pigz \
    > whosonfirst-data-admin-${COUNTRY_CODE}.geojsonl.gz

# CONVERT TO GEOPACKAGE FORMAT
ogr2ogr \
  -f GPKG \
  whosonfirst-data-admin-${COUNTRY_CODE}.gpkg \
  /vsigzip/whosonfirst-data-admin-${COUNTRY_CODE}.geojsonl.gz
```

<img width="614" alt="Screenshot 2020-04-15 at 20 55 29" src="https://user-images.githubusercontent.com/738069/79377664-5059c280-7f5c-11ea-9372-c2b889a8c6c0.png">

@justinelliotmeyers could you please give this a whirl in `QGIS` (61MB download) and let me know how you get on?
https://s3.amazonaws.com/geocodeearth-missinglink/whosonfirst-data-admin-nz.gpkg.zip

**Comment by thisisaaronland** [comment]
Work in progress:

* https://github.com/whosonfirst/go-whosonfirst-iterate-fs
* https://github.com/whosonfirst/go-whosonfirst-iterate-fs/blob/master/cmd/count/main.go

**Comment by missinglink** [comment]
ping @justinelliotmeyers did you get a chance to try out the `GeoPackage` download?

**Comment by justinelliotmeyers** [comment]
@missinglink not yet - I'll make time this weekend to look. Sorry, honestly busy with tons of projects and side projects.

**Comment by justinelliotmeyers** [comment]
@missinglink The polygons look good. I didn't realize there was this much data in here, overlapping sources, and tons of attributes. Its amazing! Is creating a different file type like this for users like me a massive project pain? seems like tons of work/ coding. It is useful to me, but if it doesn't make sense for a larger group of users, I'd hate for people to waste their time.  Thanks!

**Comment by nvkelso** [comment]
We're working on this now, and hope to have an announcement soon.

**Comment by justinelliotmeyers** [comment]
closing this as the shapefile dumps have been built: https://geocode.earth/data/whosonfirst/

**Comment by missinglink** [comment]
I set the shapefile build to check for changes every 4-6 hours or so (same as the other distribution files), if the files are ever lagging by more than a day relative to GitHub, please ping me for manual intervention.

**Comment by nvkelso** [comment]
Thanks @missinglink !
