### ISSUE TITLE
Outdated Properties

### ISSUE THREAD

**Issue by Guilherme-B** [whosonfirst-data/whosonfirst-data#1836]
The [properties json](https://raw.githubusercontent.com/whosonfirst/whosonfirst-properties/master/aliases/all_properties.json) is missing the following:

- "src:altlabel"
- "name:deu_at_x_preferred"
- "name:deu_ch_x_preferred"
- "name:eng_ca_x_preferred"
- "name:eng_gb_x_preferred"
- "name:por_br_x_preferred"
- "name:srp_ec_x_preferred"
- "name:srp_el_x_preferred"
- "name:szy_x_preferred"
- "name:zho_cn_x_preferred"
- "name:zho_hk_x_preferred"
- "name:zho_tw_x_preferred"

Came across these in the Costa Rica bundle.

**Comment by stepps00** [comment]
Thanks @Guilherme-B - these properties have all been added to WOF since the `property.json` file was introduced. Going forward, I need to have a think about how to approach updates to the `property.json` file, as there are 250+ admin repos that need to be crawled to verify/adjust the json file with any new/removed properties.

Let me know if you have any thoughts.. in the meantime, I'll adjust to add these properties (and take a look into `src:altlabel`, that's odd).

**Comment by Guilherme-B** [comment]
Well @stepps00 , we can do this the old-fashioned way, though it will take a long time and it will be rather inefficient, I am doing something similar though.
Loop through the possible list of countries (alpha2 codes) and download them - alternatively you can just crawl GitHub's API and download the repos matching a regex - process each one of them pushing the tags onto a set, these will be your unique entries.

Fact is, it makes far more sense to do this beforehand, making sure a tag is included in the properties file whenever its added.

**Comment by stepps00** [comment]
https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/all_properties.json has been updated with the most recent property additions.
