### ISSUE TITLE
Duplicate Entities

### ISSUE THREAD

**Issue by Guilherme-B** [whosonfirst-data/whosonfirst-data#1837]
Recent Bundles often contain duplicate entities, though it seems to be recent. For instance in Colombia, entity 890452015 is duplicated:
![image](https://user-images.githubusercontent.com/38859748/81222988-25074800-8fdd-11ea-9290-cf351e9d25d8.png)

Is this normal? Or does the `lastmodified` set to `-1` flag a removed version hence deprecated, and the other one is to be considered?

**Comment by stepps00** [comment]
Hey @Guilherme-B - this looks similar to an issue tracked by Pelias, more info [here](https://github.com/pelias/whosonfirst/issues/508#issuecomment-624867013). The issue has to do with the `is_alt` flag.

Take a look at that issue, you may be able to grab the newest bundle for a fix.

**Comment by missinglink** [comment]
Hey @stepps00 actually my fix won't hold unfortunately
https://github.com/whosonfirst-data/whosonfirst-data-admin-gb/blob/master/data/101/853/501/101853501-alt-whosonfirst.geojson

This record shares an alt name the same as the src name from the default geom

**Comment by missinglink** [comment]
I'll add a new column to the SQLite db tomorrow that should fix this

**Comment by stepps00** [comment]
Oof.. thanks @missinglink 

So just to clarify, the issue occurs when a record's `src:geom` property value is identical to the source of an alt file? Seems like this is a sliver of cases, mostly `whosonfirst`-source related.. but good catch!

**Comment by missinglink** [comment]
I think maybe it was ambitious on my part to start including alt geoms in the SQLite dist files.

When I ported the Go code it had support for this but seems it had never been tested out in dist files that were being served up to the public.

Anyway, I think it's for the best to include alt files in the SQLite dbs and encourage their adoptance so I'll fix it rather than reverting to how it was.

**Comment by missinglink** [comment]
This is the issue describing the bug and the solution https://github.com/whosonfirst/go-whosonfirst-sqlite-features/issues/7

**Comment by missinglink** [comment]
Sorry @Guilherme-B if this doesn't make sense.

The dist files are now being generated using a different method and hosted by us (Geocode Earth).

The versions which were available on `dist.whosonfirst.org` were quite old and as such didn't represent the latest database schema.

Prior to 2020 the `geojson` table used the `ID` column as a primary key, and as such there was only ever one row per ID.

At some point the schema changed to allow multiple rows sharing the same ID, these other rows are "alternative geometries" for the same place, but are marked `is_alt=1` to indicate that they are not the default geometry for that ID.

The bug is in how the unique constraint is being enforced on the database table.

And actually you might not have noticed the bug were talking about... ;)

To answer your question, is wasn't normal, but now it is normal.

From now on it's possible for multiple rows in the geojson table to share the same ID but there should only ever be one with `is_alt=0`

If you'd like to restore the old behavior in your application then you will need to add `WHERE is_alt=0` to your SQL queries to only return the row corresponding to the default geometry per ID.

**Comment by Guilherme-B** [comment]
@missinglink  thank you.

If you don't mind I'll make a few other questions then:
- Does the `is_alt=0` represent the "actual" geometry, or what is the reasoning behind having multiple versions?
- Is the WOF project now being handled by Geocode Earth, or is it still open source and handled/modified by its contributors only (which seems to be @stepps00 on a free-time basic mostly)?

**Comment by missinglink** [comment]
Stephen is better suited to answer but our position is that we required more up-to-date dist files for Pelias and so we started generating them and hosting them ourselves.

Our goal is to publish the data verbatim as you would find it in the GitHub repo, which is why the alt geometries are included.

:zzz:

**Comment by missinglink** [comment]
The schema change pre-dated our involvement: https://github.com/whosonfirst-data/whosonfirst-data/issues/1793#issuecomment-587909018

**Comment by stepps00** [comment]
> Does the is_alt=0 represent the "actual" geometry, or what is the reasoning behind having multiple versions?

The `0` means the entry contains the "default" geometry of in the `{id}.geojson` file, a `1` represents the entry is the (or one of the) "alt" geometries in one of the `{id}-alt-*.geojson` files. The entries in your original comment image should represent [this "default" file](https://github.com/whosonfirst-data/whosonfirst-data-admin-co/blob/master/data/890/452/015/890452015.geojson) and [this "alt"  file](https://github.com/whosonfirst-data/whosonfirst-data-admin-co/blob/master/data/890/452/015/890452015-alt-quattroshapes.geojson).

> Is the WOF project now being handled by Geocode Earth, or is it still open source and handled/modified by its contributors only (which seems to be @stepps00 on a free-time basis mostly)?

The [Who's On First](https://github.com/whosonfirst) (including [Who's On First data](https://github.com/whosonfirst)) project is maintained by various contributors.. which is still maintained under an [open license](https://whosonfirst.org/docs/licenses/).

As @missinglink mentioned, until recently distributions were maintained on the [dist.whosonfirst.org](https://dist.whosonfirst.org) site. The Geocode Earth folks have been kind enough to sponsor them since then, maintained [here](https://geocode.earth/data/whosonfirst).

As for this specific issue, it looks like it will be taken care of this week. I don't think there is a data fix needed, so I'll suggest closing this issue for now and tracking on the Geocode Earth/Pelias side.

**Comment by missinglink** [comment]
This issue can be closed IMO.

What might be lacking is some documentation on the SQLite schema for users.
