### ISSUE TITLE
Copenhagen sections have wrong names

### ISSUE THREAD

**Issue by HadiSDev** [whosonfirst-data/whosonfirst-data#1872]
Copenhagen Municipality is called "Københavns Kommune" in danish, however, in the dataset, it suggests the English name as the danish name:
https://spelunker.whosonfirst.org/id/1159297727/

![image](https://user-images.githubusercontent.com/10367624/88664834-f8dffc80-d0dd-11ea-866b-1ff900bac620.png)

**Comment by nvkelso** [comment]
I'm not sure why it's in English there, might be an artifact of how the data was imported? But we recommend using the localized `name` properties instead. Is it an issue there? @stepps00 for some 👀 .

**Comment by stepps00** [comment]
Hi @HadiSDev - thanks for the issue.

The properties shown in your screenshot are derived directly from the [`dk-geodk`](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/dk-geodk.json) source. I agree that the source data suggests the Danish name is "Copenhagen" for this place, which does seem odd. I can take a look at the source data files and adjust if a mistake was made during the import.

Looking at the `name:` properties, it looks like this English name was used to update the Danish translation.. so, I'll file a PR to fix.

```
    "name:dan_x_preferred":[
        "Copenhagen"
    ],
    "name:dan_x_variant":[
        "K\u00f8benhavn"
    ],
...
    "name:eng_x_preferred":[
        "Copenhagen"
    ],
```

Curious, do you see other issues when browsing admin data in Denmark? Do you see this occurring in other locality records? I'll crawl the data in Denmark for other cases, but curious if this is more widespread.

**Comment by stepps00** [comment]
I reviewed the other `dk-geodk:komhavn` properties in the localadmin records of Denmark, which look correct. This issue only affects the Copenhagen record, likely because I modified the name string as part of the import process to fix https://github.com/whosonfirst-data/whosonfirst-data/issues/1102.

The above PR fixes issues with the `"name:dan_x_preferred"`, `"label:dan_x_preferred"`, and `"dk-geodk:komhavn"` properties.
