### ISSUE TITLE
Wrong name for Salgar

### ISSUE THREAD

**Issue by desiderantes** [whosonfirst-data/whosonfirst-data#1892]
There are 3 towns in Colombia Called Salgar:

-  [Salgar (Antioquia)](https://www.wikidata.org/wiki/Q1525126)
-  [Salgar (Atlántico)](https://www.wikidata.org/wiki/Q98756097)
-  [Puerto Salgar (Cundinamarca)](https://www.wikidata.org/wiki/Q1524761)

This DB gives the second one the name of the third one, and duplicates the name for counties (which do not exist)

**Comment by stepps00** [comment]
Thanks @desiderantes - I think these are the WOF records you're referring to:

-  [Salgar (Antioquia)](https://www.wikidata.org/wiki/Q1525126): https://spelunker.whosonfirst.org/id/1108699999/
-  [Salgar (Atlántico)](https://www.wikidata.org/wiki/Q98756097): https://spelunker.whosonfirst.org/id/1343285443/
-  [Puerto Salgar (Cundinamarca)](https://www.wikidata.org/wiki/Q1524761): https://spelunker.whosonfirst.org/id/1108700697/

> This DB gives the second one the name of the third one, and duplicates the name for counties (which do not exist)

It looks like the second record ([Salgar (Atlántico)](https://spelunker.whosonfirst.org/id/1343285443/)) needs updated names. Rather than "Puerto Salgar", the names for this place should be "Salgar". Are there additional changes that are needed?

**Comment by desiderantes** [comment]
The name should be "Salgar", and there's the old name "San Antonio de Salgar" which is still used sometimes.
