### ISSUE TITLE
Locality geometry mismatch

### ISSUE THREAD

**Issue by taygun** [whosonfirst-data/whosonfirst-data#1958]
Hello 👋 
How is the geometry for this locality generated https://spelunker.whosonfirst.org/id/1125935985/?
In spelunker I see the locality polygon drawn on map, but checking the github data the geometry for this locality is a point  https://github.com/whosonfirst-data/whosonfirst-data-admin-ee/blob/master/data/112/593/598/5/1125935985.geojson

**Comment by nvkelso** [comment]
The polygon you see in Spelunker is for the parent. Instead this feature is just a point geometry originally from the Quattroshapes point gazetteer, which merged the records from GeoNames (GN) and Where On Earth (WOE).

**Comment by stepps00** [comment]
@taygun a bit confusing since the Spelunker tool and GitHub are out of sync at the moment, but the polygon you're seeing in the Spelunker is the geometry for this locality's parent: https://github.com/whosonfirst-data/whosonfirst-data-admin-ee/blob/master/data/171/331/094/3/1713310943.geojson

Data source: https://github.com/whosonfirst/whosonfirst-sources/blob/main/sources/ee-mamt.json
