### ISSUE TITLE
whosonfirst-data-postalcode-gb August 2021 update

### ISSUE THREAD

**Issue by tomtaylor** [whosonfirst-data/whosonfirst-data#1960]
Unfortunately I can't generate a pull request for this in the Github UI - it's too big.

I've updated https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb with the latest August 2021 release of the ONS Postcode Directory. This was created using the latest version of https://github.com/whosonfirst/wof-sync-os-postcodes.

Along with creating new postcodes and ceasing any newly terminated postcodes, it also:

- Updates the formatting on all updated/created features using the latest formatting in `go-whosonfirst-export`. Typically, this only affects the whitespace after the comma in an array.
- Changes the EDTF output on any newly created/updated features to use the new EDFT spec (replacing `"uuuu"` with `""`)

This is sitting in my branch here: https://github.com/tomtaylor/whosonfirst-data-postalcode-gb/tree/august-2021-sync

**Comment by tomtaylor** [comment]
cc @stepps00 @vicchi @missinglink

**Comment by missinglink** [comment]
oof, yeah I'm trying to get it to work on the CLI, big repo!

**Comment by tomtaylor** [comment]
Yeah, landing shortly is the script that gets everything set up on the 64GB VM with ram disk, needed to actually perform the sync! 😬

**Comment by missinglink** [comment]
Is git having difficulties because of the amount of changes made in this PR, or are there relatively few changes but the amount of total files in the repo is the problem?

**Comment by tomtaylor** [comment]
I think it's the ~3M files in the repo - reading lots of tiny files really hurts the performance. This has a reasonable number of changes, but no more than previous updates.

**Comment by tomtaylor** [comment]
Added some docs about performing the sync for future generations to discover: https://github.com/whosonfirst/wof-sync-os-postcodes#performing-the-sync

**Comment by tomtaylor** [comment]
I'd love to get this merged! Who should I speak to?

**Comment by missinglink** [comment]
Ok, I figured out a workflow using `bare` clones which would allow this to get reviewed cc/ @stepps00 

```bash
mkdir /tmp/whosonfirst-data-postalcode-gb

git clone \
  --progress \
  --branch august-2021-sync \
  --depth 2 \
  --single-branch \
  --bare \
  https://github.com/tomtaylor/whosonfirst-data-postalcode-gb.git \
  /tmp/whosonfirst-data-postalcode-gb

git --git-dir=/tmp/whosonfirst-data-postalcode-gb \
  diff dd818d2605da8684cc2d5d29c604596a97e6661a d43cd53695d4af055da6acc67db3a68b21c9e3a0
```

**Comment by missinglink** [comment]
The diff is `3.9GB` 😱 so I won't be sharing it 😆, it took several minutes to compute but not ♾️ 

Just looking at the top change, there seems to be some potential issues (maybe not worth worrying about?):

- some extra whitespace added after the `"wof:belongsto"` elements
- removal of the "date:*" tags
- removal of `wof:hierarchy` self-reference

note: you can extract a file from a bare repo for spot-checking with:
```
git --git-dir=/tmp/whosonfirst-data-postalcode-gb \
  show d43cd53695d4af055da6acc67db3a68b21c9e3a0:data/116/071/277/8/1160712778.geojson
```

<img width="357" alt="Screenshot 2022-02-11 at 15 04 24" src="https://user-images.githubusercontent.com/738069/153605573-12487129-067e-4583-bdc7-d655d995771b.png">

**Comment by missinglink** [comment]
actually it seems most of the changes in this changeset are related to these properties changing and no actual geometry changes as you'd expect to see, so maybe this is mostly as a result of changes to the `exportify` command rather than related to the postcode update itself.

there are certainly some other records where the geometry changes, but they seem to be in the minority:

<img width="552" alt="Screenshot 2022-02-11 at 15 15 31" src="https://user-images.githubusercontent.com/738069/153607572-5d087aa3-0584-4595-aab8-2cdab887344a.png">

**Comment by tomtaylor** [comment]
@missinglink yeah, that's correct. Everything it put through the Go exporter, so there are decisions made there that have created some churn in the diffs. Some geometry may change _slightly_ as new properties have been built in the postcode and the underlying centroid has moved.

**Comment by thisisaaronland** [comment]
Curious about how/where/why the `date:upper_*` and `date:lower_*` properties got removed. I double checked that the `go-whosonfirst-export` is setting them where applicable:

https://github.com/whosonfirst/go-whosonfirst-export/blob/main/properties/edtf.go#L61-L83
https://github.com/whosonfirst/go-whosonfirst-export/blob/main/properties/edtf.go#L118-L140

Nothing in the export code should be explicitly removing properties unless something else is invoking `export.RemoveProperties` :

https://github.com/whosonfirst/go-whosonfirst-export/blob/main/properties.go#L86

**Comment by orangejulius** [comment]
Hi folks,
It really looks like this is pretty close, great work Tom.

Is it possible to run `exportify` over all the current data to generate a PR or series of commits that include just those changes? Then we'd be able to generate a new diff with _just_ the changes in data. I could see that being to much work or it might make it easier to make progress.

### Postalcode cities

We actually just got a report from a Geocode Earth customer that one postalcode [M41 9PT](https://spelunker.whosonfirst.org/id/470911809/) is parented by the locality of [Stretford](https://spelunker.whosonfirst.org/id/1125882177/) when it really (according to the [Royal Mail](https://www.royalmail.com/find-a-postcode)) should be in nearby [Urmston](https://spelunker.whosonfirst.org/id/1125957071/).

I checked and even in the latest ONS data, the coordinates for the M41 9PT postalcode really do lie within the boundary of Stretford. So is it possible the Royal Mail has data linking postalcodes to city names that is listed somewhere else? This problem is pretty common globally and is what led us to create the Pelias [postal cities](https://github.com/pelias/postal-cities) mapping, though it's not helpful here _yet_.

If that data exists with a compatible license out there I'd be happy to help try to integrate it into this script.

**Comment by tomtaylor** [comment]
Thanks @orangejulius! I’m happy to try and land a PR containing just the formatting and other property changes from running exportify, followed by another which does the August 2021 update (there’s a November 2021 update now, and I think there’s one due in Feb too). That should make it a bit easier to review.

On the postal cities, unfortunately I think all the address info is under a restrictive license from Royal Mail/Ordnance Survey. I think that’s the Address Base product. We managed to get the postcodes out of them, but they’re still clinging onto the rest. I’ll point some folks I know in government who are much closer to this stuff at this thread and get their take on it.

@thisisaaronland strange - it’s possible that I was using older version of the library. I’ll check.

**Comment by tomtaylor** [comment]
> Curious about how/where/why the `date:upper_*` and `date:lower_*` properties got removed. I double checked that the `go-whosonfirst-export` is setting them where applicable:

I've had a look - I think the diff has been generated back to front, so they're actually being added in this PR, not removed!

**Comment by tomtaylor** [comment]
cc: @orangejulius @missinglink

OK, I've made a new branch in which I've updated the unspecified EDTF dates to the ISO standard, and run exportify over for formatting and other minor property changes.

https://github.com/tomtaylor/whosonfirst-data-postalcode-gb/tree/exportify

If we can land this, then I'll open a separate PR syncing the latest ONS postcode updates.

**Comment by tomtaylor** [comment]
Once more with feeling! I'd really love to get this landed - GB post codes are now 9 months out of date. Who can help get this merged?

**Comment by missinglink** [comment]
Hi @tomtaylor sorry I don't have merge access, it's all handled by @stepps00

**Comment by tomtaylor** [comment]
Just a heads up that @missinglink and I have been chatting about how we can land changes like this faster in the future. We rely on the postcode data being current because our business uses it to geocode vacancies.

I spoke to @thisisaaronland and volunteered to be a maintainer of https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb. I'm going to try land these changes with review where possible from others, and then follow up with the August 2022 release when it's out.

**Comment by missinglink** [comment]
I had another look at this PR today, just looking at the diff between the HEAD of the upstream repo and the `august-2021-sync` feature branch (see method below).

I noticed that the diff is significantly smaller now since https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/commit/0c0d2b8f4d8910c55281f185aa03d50e57415275 & https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/commit/b37d47eaf68f9c58c61753ac8079524cb7337e58 landed.

One thing I noticed is that the `wof:lastmodified` timestamp is updated even for records where nothing else in the body of the document changed. It's probably not a big deal but maybe it's a quick fix to the Go script leave those as a no-op?

eg:
<img width="310" alt="Screenshot 2022-08-08 at 15 43 08" src="https://user-images.githubusercontent.com/738069/183433662-aebf324b-958a-49bf-8ae6-bfc819a1d518.png">

**method**

```bash
git clone   \
  --progress --depth 2 --single-branch --bare \
  --branch august-2021-sync \
  https://github.com/tomtaylor/whosonfirst-data-postalcode-gb.git \
  "${WORK}/whosonfirst-data-postalcode-gb"
```

```bash
git --git-dir="${WORK}/whosonfirst-data-postalcode-gb" \
  remote add upstream https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb.git
  
git --git-dir=/work/wof/whosonfirst-data-postalcode-gb \
  fetch upstream
```

```bash
git --git-dir=/work/wof/whosonfirst-data-postalcode-gb \
  diff b37d47eaf68f9c58c61753ac8079524cb7337e58 dd818d2605da8684cc2d5d29c604596a97e6661a
```

**Comment by thisisaaronland** [comment]
That _should_ be accounted for in `go-whosonfirst-export` but it's possible there are outstanding bugs or edge-cases: 

* https://github.com/whosonfirst/go-whosonfirst-export/blob/0d4f48214076d8c4d2cf1e9a21dc2c042a781d22/export.go#L46

* https://github.com/whosonfirst/go-whosonfirst-export/blob/0d4f48214076d8c4d2cf1e9a21dc2c042a781d22/export_test.go#L377

**Comment by missinglink** [comment]
I ran the same file from my screenshot though the test suite and it didn't indicate a change, so maybe it's an artefact of a previous run or something? doesn't seem to be a bug 🤔 

```diff
diff --git a/export_test.go b/export_test.go
index 19ae6cc..5259c22 100644
--- a/export_test.go
+++ b/export_test.go
@@ -383,12 +383,14 @@ func TestExportChangedWithUnchangedFile(t *testing.T) {
                t.Fatal(err)
        }

-       body := readFeature(t, "no-changes.geojson")
+       feature := readFeature(t, "1160712886.geojson")
+       existing := make([]byte, len(feature))
+       copy(existing, feature)

        var buf bytes.Buffer
        wr := bufio.NewWriter(&buf)

-       changed, err := ExportChanged(body, body, opts, wr)
+       changed, err := ExportChanged(feature, existing, opts, wr)

        if err != nil {
                t.Fatal(err)
```

**Comment by tomtaylor** [comment]
It looks like it's using an old version of `go-whosonfirst-export`, 0.4.0. I'll upgrade to the latest and run again and see how that does.

**Comment by nvkelso** [comment]
Thanks for all your help @tomtaylor! Happy to have you onboard as a maintainer :)

**Comment by tomtaylor** [comment]
OK, once more with feeling! Two PRs landed which should get us to the August 2021 sync. We can deal with the August 2022 update when it's released.

https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/6
https://github.com/whosonfirst-data/whosonfirst-data-postalcode-gb/pull/7

**Comment by missinglink** [comment]
The August 2022 update is now available 🎉 

https://geoportal.statistics.gov.uk/datasets/ons-postcode-directory-august-2022/

**Comment by tomtaylor** [comment]
Closing this as completed. New sync to follow!
