### ISSUE TITLE
Wenigumstadt (ID 1393659815) has wrong properties

### ISSUE THREAD

**Issue by golden-spiral** [whosonfirst-data/whosonfirst-data#1998]
https://spelunker.whosonfirst.org/id/1393659815/
reads

county	[Darmstadt-Dieburg 102063549](https://spelunker.whosonfirst.org/id/102063549/)
local admin	[Schaafheim 1377693209](https://spelunker.whosonfirst.org/id/1377693209/)
macrocounty_id	404227581
region	[Hesse 85682531](https://spelunker.whosonfirst.org/id/85682531/)

It must be

county	[Aschaffenburg 102063553]
local admin	[Großostheim 101906951]
macrocounty_id	404227569 Unterfranken
region	[Bavaria 85682571]

Source: Me and https://de.wikipedia.org/wiki/Wenigumstadt

**Comment by stepps00** [comment]
Thanks @golden-spiral! I think this issue is being caused by the label centroid of this record falling within the geometry of it's neighbor: https://spelunker.whosonfirst.org/id/101906951/

Once that label centroid is corrected, we can [re-PIP](https://github.com/whosonfirst/whosonfirst-cookbook/blob/main/how_to/setting_up_pip_service.md) the record to update it's hierarchy. As part of this issue, we'll look into other records in Germany with label centroids that fall outside of their geometries and update those, too.

**Comment by golden-spiral** [comment]
Any action I can do or is this now in your hands?
