### ISSUE TITLE
These France "country" features are regions

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#2]
These are the overseas regions of France, they aren't top-level countries. They should be superseded as follows

They do have ISO A2 country codes, but they also have ISO region codes inside of France. 

id  iso lastmodified    name    parent_id   path    source  parent_id_old   note    superseded_by
85632351    RE  1439244129  France  85633147    data/856/323/51/85632351.geojson    naturalearth    102193527   region of france    85671199
85632423    GP  1439244135  France  85633147    data/856/324/23/85632423.geojson    quattroshapes   102191575   region of france    85671209
85632233    GF  1439244149  France  85633147    data/856/322/33/85632233.geojson    quattroshapes   -1  region of france    85671195
85632523    YT  1439244190  France  85633147    data/856/325/23/85632523.geojson    quattroshapes   102191573   region of france    85671203
85632531    MQ  1439244192  France  85633147    data/856/325/31/85632531.geojson    quattroshapes   102191575   region of france    85671191

**Comment by stepps00** [comment]
@nvkelso, in the first example, we'd be superseding the `country` of [Reunion](https://whosonfirst.mapzen.com/spelunker/id/85632351/#9/-21.1147/55.5320) to the `region` of [La Réunion](https://whosonfirst.mapzen.com/spelunker/id/85671199/#10/-21.1163/55.5400). To be clear - since these five records are not true countries, but rather overseas regions of France, we're superseding `country` records to `region` records?

Also, which of the `alt name` fields are we promoting? Would the name for this region change from "La Réunion" to "Reunion"?

**Comment by nvkelso** [comment]
Good catch. The `alt name` comment is spurious and related to the old country record (where the name is bad as France, but the alt name had the region name good). I spot checked the region names in the "new" supersedes records and they're all good (modulo ASCII-2, but that's for tomorrow).

WARNING that there is extra **concordance** data and other goodness in the "old" superseded-by records that we should also bring over.

**Comment by stepps00** [comment]
Steps for updating:

- Add `edtf:deprecated` date and `mz:is_current:0` property to `country` records
- Supersede `country` records into `region records
- Add `wof:lang*`, `name:`, and `wof:concordances` properties to `region` records
- Update `wof:parent_id` for all `region` records
