### ISSUE TITLE
Duplicated ID 102524727 in whosonfirst-data-admin-us

### ISSUE THREAD

**Issue by slaperche-zenly** [whosonfirst-data/whosonfirst-data#2001]
There are 2 shapes with the ID 102524727:
- [102524727.geojson](https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/fbdf31344e769b841de6de5511f0c24208db2a56/data/102/524/727/102524727.geojson)
- [1746879067.geojson](https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/fbdf31344e769b841de6de5511f0c24208db2a56/data/174/687/906/7/1746879067.geojson)

They have no supersede{s,d} relation but represent the same place.

Maybe `102524727` should supersedes `1746879067` (based on the name)?

**Comment by stepps00** [comment]
Hey @slaperche-zenly - with this case, 1746879067 is a historical record for El Paso Municipal Airport. In this record, you'll see a `"mz:is_current": 0`, which indicates the place is no longer "current" in Who's On First. The record also has `edtf:` properties that can be used to determine when the place was current/active. 102524727 is the current record for El Paso International Airport. So these places do represent different places in time and property flags look ok.

That being said, I do see the `wof:id` values in [1746879067](https://github.com/whosonfirst-data/whosonfirst-data-admin-us/blob/master/data/174/687/906/7/1746879067.geojson) looks incorrect..

@thisisaaronland I think the fix is to just update the top-level `id` in this record, but flagging this since it's an airport record.

**Comment by slaperche-zenly** [comment]
Ha I didn't know about those properties, thanks for the details @stepps00
