### ISSUE TITLE
Data hierarchy missing for Yarrabilba, QLD, AU

### ISSUE THREAD

**Issue by pravink** [whosonfirst-data/whosonfirst-data#2004]
- Issue Description  
we found that the suburb Yarrabilba, QLD, AU is missing from the whosonfirst admin data

- Possible Solution/Data Source
If someone can guide me how add this data in whosonfirst admin data then I am happy to contribute here.

Thanks,
Pravin

**Comment by nvkelso** [comment]
@stepps00 can you help Pravin, please?

**Comment by stepps00** [comment]
Hey @pravink can you point us to an authoritative data source for Australia? In the past, Who's On First has imported [PSMA](https://github.com/whosonfirst/whosonfirst-sources/blob/main/sources/aus-psma.json) and [ABS](https://github.com/whosonfirst/whosonfirst-sources/blob/main/sources/ausstat.json) to update administrative records.. but the data Who's On First maintains is likely outdated in some places and missing some features (like Yarrabilba).

Pointing to a data source would be a great first step, then we'd need to compare with Who's On First to see what changes are needed (which may also be tracked in another issue).

**Comment by missinglink** [comment]
<img width="901" alt="Screenshot 2022-06-27 at 13 09 37" src="https://user-images.githubusercontent.com/738069/175928200-bdfe9d3d-2c7f-44fb-8ddc-f0fcc86890e8.png">

**Comment by pravink** [comment]
@stepps00 if you have any steps handy for loading these geojson files to wof admin data then could you please share with those with me?

**Comment by stepps00** [comment]
Hey @pravink - WOF's Australia admin repo lives here: https://github.com/whosonfirst-data/whosonfirst-data-admin-au

This is where we'd want to maintain a new record for Yarrabilba. Since WOF doesn't have a record for this place already, we should be able to add it through a PR, as long as its formatted appropriately.

Here are some examples of locality records already present in WOF: [Sydney](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-au/master/data/101/932/003/101932003.geojson), [Currajong](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-au/master/data/101/934/255/101934255.geojson), [West Mackay](https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-au/master/data/101/935/609/101935609.geojson)

Feel free to open a PR with a new Yarrabilba record formatted similar to the above examples in the Australia admin repo and flag any questions you may have there. Alternatively, since this process involves using some [formatting tools](https://github.com/whosonfirst/py-mapzen-whosonfirst-utils), I can also create a PR with a new record and flag you there.

**Comment by pravink** [comment]
HI @stepps00  Thanks for pointing out above links..  I did followed below steps but looks like need more guidance here.. 
1. download the shapefile: wget https://data.gov.au/data/dataset/bdcf5b09-89bc-47ec-9281-6b8e9ee147aa/resource/53c24b8e-4f55-4eed-a189-2fc0dcca6381/download/may22_adminbounds_gda94_shp.zip
2. unzip it
3. find a specific dbf file: find MAY22_AdminBounds_GDA94_SHP -type f -name '*.dbf' -print0 | xargs -0 grep -i 'Yarrabilba'
4. locate the directory  - and got the shapefile under it-  using below shapefile - and not meshblocks and sa1 an sa2.
		MAY22_AdminBounds_GDA94_SHP/Localities_MAY22_ALLSTATES_GDA94_SHP_103/Localities/Localities MAY 2022/Standard/qld_localities.shp
5. convert the shapefile to csv using: ogr2ogr -f CSV -dialect sqlite -sql "select AsGeoJSON(geometry) AS geom, * from qld_localities" qld_localities.csv qld_localities.shp
6. extracted the yarrabila record from csv: less -n qld_localities.csv | grep 'Yarrabilba' > ya.csv  
7. git cloned and installed - https://github.com/whosonfirst/py-mapzen-whosonfirst-utils   
8. Not sure exactly which script to use to convert this feature polygon to wof record. 
9. if you have list of steps to use scripts mentioned in above repo then could you please share those with me. 
10. I am happy to raise PR myself. just a little bit of learning curve first time.. :)

**Comment by stepps00** [comment]
Thanks for the detailed steps here.. all of this looks good, but there are several steps required to convert a source shapefile or feature to a WOF record (step 8); there is no single script that will do that work.

I'd recommend looking at the three locality examples in https://github.com/whosonfirst-data/whosonfirst-data/issues/2004#issuecomment-1170619414, and cloning one of them as a new record in the `whosonfirst-data-admin-au` repo, updating the property values and geometries as needed for the Yarrabilba record.

You can use this unique ID for the new Yarrabilba record: `1779794981`.

The PR you'd create in the repo would have a new `1779794981.geojson` record (full path: `data/177/979/498/1/1779794981.geojson`) and you'd want to update all of the properties to reference Yarrabilba. You'd also want to update the geometry.

Once that's complete, you can use the `wof-exportify` tool in the https://github.com/whosonfirst/py-mapzen-whosonfirst-utils repo you cloned, passing the new ID as an arg. This would validate the record and ensure there are no issues with the Who's On First distributions.

Quite a few steps here, so feel free to open a PR in the `whosonfirst-data-admin-au` repo - I'm happy to leave comments there. I'd also like to craft a doc in our [cookbook repo](https://github.com/whosonfirst/whosonfirst-cookbook) documenting how this was done, it would be helpful for future contributions.

**Comment by pravink** [comment]
Hi @stepps00 

Sorry that I didn't get a chance earlier to raise a PR but its now ready for your review.

Thanks,
Pravin!
