### ISSUE TITLE
New French 2016 regions

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#208]
From the Geonames list:

```
From 1st January [2016-ed] France has a new division
(https://en.wikipedia.org/wiki/Regions_of_France).
```

**Comment by stepps00** [comment]
The **WOF S3 Dropbox misc folder** now contains a file with new geometries for 2016 French regions, [link here](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%20208/Import_NewRegions.geojson). Contents/attributes:

The geojson file contains seven new geometries that should be imported as new regions in France; these shapes were created by combining existing French regions. Since the restructuring of French regions [did not change any borders](https://en.wikipedia.org/wiki/Regions_of_France#Reform_and_mergers_of_regions), this should be a simple supersedes/supersedes_by task.

**wof:name**
* New `wof:name` field added for each new region. Sources [here](https://en.wikipedia.org/wiki/Regions_of_France) and [here](http://www.insee.fr/fr/methodes/nomenclatures/cog/).

**name:fra_x_preferred**
* If the new region had a non-English transliterated name (_ex: Île-de-France_), it was added to this field as a new `name` field.

**wof:supersedes**
* This string field contains any `wof:id`s of any records that the new record supersedes.

**Comment by nvkelso** [comment]
LGTM

**Comment by stepps00** [comment]
Files removed from S3; the PR mentioned above should include all work required to fix this issue.
