### ISSUE TITLE
1796406393 has string wof:id value

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#2208]
https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data-admin-pl/master/data/179/640/639/3/1796406393.geojson

**Comment by nvkelso** [comment]
That's weird! I looks like all 7 new records in https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/commit/e40251664bef85cd9b917ec53d7e34487616aae8 have the same string (quoted) id property value problem.

While it's easy to fix these 7, let's spend a little time understanding how this got to be merged...

@stepps00 do you remember how these features were created? What tools were used?

@thisisaaronland What happens when the exportify tool sees a quoted WOF id, will it convert to int automatically as part of the validation subprocess? Is that same/diff between Python and Go? The PIP tool was also invoked here so same question.

Also raises point that probably we need a GH Action that reviews all changed files to make sure they validate...

**Comment by thisisaaronland** [comment]
The Python code does not explicitly (re)case `wof:id` as an int if the property is already set:

https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L85-L103

The Go validation code does not either as it turns out:

https://github.com/whosonfirst/go-whosonfirst-validate/blob/main/validate.go#L10-L28

I can fix the latter quickly. As it happens, the export code doesn't check either. That too is easy enough to fix:

https://github.com/whosonfirst/go-whosonfirst-export/blob/main/properties/wofid.go#L10-L29

**Comment by nvkelso** [comment]
Data fix in https://github.com/whosonfirst-data/whosonfirst-data-admin-pl/pull/55/files.

This only fixes obvious bugs from new records added in the same original PR, including for 1796406393. It doesn't crawl all the repos looking for or fixing the problem with the assumption this was a strange one-off problem.

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-feature/releases/tag/v0.0.28

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-validate/releases/tag/v0.4.0

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/wof-cli/releases/tag/v0.0.22

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-validate-wasm/releases/tag/v0.0.7

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/go-whosonfirst-validate-wasm/releases/tag/v0.0.8

This release adds WASI (wasip1) support which is what should (eventually) allow a Python-based validator package to use the same code defined in `go-whosonfirst-validate`. See also:

* https://go.dev/blog/wasi
* https://millsfield.sfomuseum.org/blog/2023/02/16/py-edtf/

**Comment by nvkelso** [comment]
Thanks for all the follow-ups, I'll update my tooling!

**Comment by stepps00** [comment]
> @stepps00 do you remember how these features were created? What tools were used?

These were created locally, through one-off Python scripts for modifying Poland data. I typically cast the feature id / `wof:id` as an int before exportifying each record.. my guess is the script didn't explicitly write those values as ints and were written as strings in that commit.

It's probably worth crawling/validating each repo to find records with string ids...
