### ISSUE TITLE
Mispelling of Guaviare, Columbia

### ISSUE THREAD

**Issue by pushing-boulders** [whosonfirst-data/whosonfirst-data#2219]
Hello.  Thank you for the wonderful Who's On First project.

I had someone share with me that the spelling of Guaviare is incorrect in the [WOF dataset](https://spelunker.whosonfirst.org/id/85670245/).

Two areas list the incorrect spelling (transposed ai, Guavaire) in `spa_x_preferred` and `ne:woe_label`.

The concordances list the correct spelling, too:  [GeoName](http://geonames.org/3681344/) and [WikiData](https://www.wikidata.org/wiki/Q272885).

I tried editing via the online GeoJSON editor, but it doesn't look like these fields are available.

Thank you for your help.

**Comment by nvkelso** [comment]
Thanks for the feedback about it being hard to use WOF Write Field to display and edit non-English names. We should fix that. At the very least we should detect that `spa` is the official language used there and also show those keys and values.

<img width="339" alt="image" src="https://github.com/user-attachments/assets/1bff74de-119a-46ed-9368-029aadfffec1">

Since there are so many names (in this case we say in the text field label 69!), we default filter the list to English. If you know the language code, in this case `spa` you can add it to the filter list and the UX will update below, like:

<img width="1139" alt="image" src="https://github.com/user-attachments/assets/909628cc-860e-4983-a03b-17257ea0b894">

Maybe we should reconsider this UX, I've found it confusing too. We've so far been erroring on side of "less" otherwise the page is very very long.

I've made the edit, moving the weird spelling to variant and keeping the single preferred value and submitted a PR https://github.com/whosonfirst-data/whosonfirst-data-admin-co/pull/17.

NOTE: We don't edit the `ne:*` or `qs:*` or other properties as those are the raw values in the other projects for reference only. Downstream users shouldn't rely on those. If you are, then there hopefully is a `wof:*` property already, or raise a discussion item to propose new props.

**Comment by nvkelso** [comment]
PR is merged, it should be in tomorrow's data distribution.

**Comment by pushing-boulders** [comment]
Hello @nvkelso.  Thank you so much for your thoughtful and detailed answer.  I appreciate it.  The UI now makes sense.  Being a first time editor, I searched the text of the page for the misspelling and didn't find it, so I quickly scanned and didn't see the field tip text that says to enter in another language.  So that's on me.  I apologize for not being more thorough.

If any UI changes are being considered, perhaps a _Show All_ button for the data?  This would allow someone new, like me, to show every field and then discover how it is housed in the UI, while also keeping it tight for those who don't want to see everything.

And no, to my knowledge, we do not use the ne: or qs: properties for data.

Thank you again for making the edit.  I now know how to make these on my own in the future thanks to you!  :smile: 

All the best!

**Comment by nvkelso** [comment]
You're very welcome, cheers :)
