### ISSUE TITLE
Incorrect Population for Panamá City

### ISSUE THREAD

**Issue by puckey** [whosonfirst-data/whosonfirst-data#2226]
The [Who’s On First entry for Panamá City](https://spelunker.whosonfirst.org/id/890445081) lists the population as 3,864,170. However, [Wikipedia](https://en.wikipedia.org/wiki/Panama_City) states the city’s population is closer to 1 million.

Could this be due to the record incorrectly linking to the country’s Wikipedia page instead of the city’s?

**Comment by justinelliotmeyers** [comment]
@nvkelso Agree with the above post, population for the city should be no more than 1.2 million

https://www.inec.gob.pa/archivos/P0705547520240202111515Cuadro%201.pdf
Provincia - 1,439,575 (page 12)
Distrito - 1,086,990 (page 12)

https://www.citypopulation.de/en/panama/cities/
Lists 1,132,969 for the city, which feels right

**Comment by nvkelso** [comment]
Doh! While the Wikipedia link was incorrect, at some point in the past Wikidata had the incorrect population value and that was the root cause.

I've corrected the population and the incorrect concordance to Wikipedia in https://github.com/whosonfirst-data/whosonfirst-data-admin-pa/pull/18, which closes this issue.

Thanks @puckey and @justinelliotmeyers!
