### ISSUE TITLE
Indicate preferred geom for reverse geocoding

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#224]
We include alternate geometries with WOF, with the primary being a mix of Natural Earth and Quattroshapes. "Primary" in this case is for map display (just like the name property).

To support reverse geocoding (point in polygon, PIP) use cases, we should indicate which geometry we think is "best". Let's set all those to Quattroshapes for now.

Reverse geocoding would like the more detailed shape, and preferably the shape that extends out into the coastal waters (10 mile, 100 mile nautical limits) – both to capture the reality on the ground to capture the greatest territorial extent, and because that serves to simplify the shape, discarding tiny coastline details that otherwise bloat file size and decrease reverse geocoding PIP performance.

**Comment by riordan** [comment]
May we never lose San Francisco to the Farallon Islands again.

**Comment by thisisaaronland** [comment]
I would like to propose that we categorize reverse-geocoding by level. Specifically:

* level 0 (default) - land-masses; basically places where fish would die, notwithstanding lakes and rivers and the like.
* level 1 - land-masses but coastal areas; places where fishermen in newfoundland would petition the federal government to seize the fishing trawlers of countries like portugal and japan; the so-called "200 mile" limit for some definition of "200 miles"

And so on. Honestly we can (and should) stop there for the time being. The notion of levels would allow for things like the Alphashapes and the notion of reverse-geocoding *at* something rather than *in* it. But that is tomorrow's problem.

All of which is to say, this is what the `mz:` namespace is for. So `mz:reversegeo` and perhaps `mz:reversegeo#1` if necessary ?

I'd like to think about fragment identifiers in keys/machinetags but at a glance nothing seems overly problematic about the idea...

**Comment by thisisaaronland** [comment]
Also, @riordan :  Nothing about the proposal so far will save you from the Farallon Islands problem absent removing them from the polygon(s) of SF entirely.

I will ask you again: What continent is Russia a part of? 

Absent some contextual logic more sophisticated than point-in-polygon (and S2 is basically just a simultaneously simpler-yet-more-precise PIP...) then you still need to have a rationale / methodology for determine where to do PIP *from*. Capital city? Geographic centroid? "Label" centroid? 

And so on...

**Comment by nvkelso** [comment]
Duplicate of https://github.com/whosonfirst-data/whosonfirst-data/issues/367.
