### ISSUE TITLE
Port Vila, capital city of the country of Vanuatu, is missing

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#258]
Here's the wikipedia page: https://en.wikipedia.org/wiki/Port_Vila

It's not found in the spelunker: https://whosonfirst.mapzen.com/spelunker/id/85632263/descendants/#6/-16.740/167.385

**Comment by stepps00** [comment]
We've recently worked on [a PR](https://github.com/whosonfirst-data/whosonfirst-data/pull/735/files) to fix https://github.com/whosonfirst-data/whosonfirst-data/issues/57, which included work in Vanuatu.

Closing issue because Who's On First does have a record for [Port-Vila, Vanuatu](https://whosonfirst.mapzen.com/spelunker/id/890416453/#8/-17.199/168.359) now!

**Comment by stepps00** [comment]
Added `name:eng_x_preferred` and `name:eng_x_variant` properties to the Port-Vila record via Boundary Issues... https://github.com/whosonfirst-data/whosonfirst-data/commit/b5975323d939a52d682277cd3d2e2172e4171f6c
