### ISSUE TITLE
Review locality for Bergen and Schilde, Belgium

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#288]
This came in through support:

"It seems your data for Belgium is off, almost every address search will return the neighborhood as locality instead of the actual locality, which in this example should be “Schilde”. So every “city” is basically wrong for our country."

![image](https://cloud.githubusercontent.com/assets/4380498/15295121/de671a2c-1b43-11e6-97b9-57ecf65479be.png)

Result from search for 49 Heidedreef, Bergen, Belgium:

"properties": {
        "id": "be/flanders:617473",
        "gid": "openaddresses:address:be/flanders:617473",
        "layer": "address",
        "source": "openaddresses",
        "name": "49 Heidedreef",
        "housenumber": "49",
        "street": "Heidedreef",
        "postalcode": "2970",
        "country": "Belgium",
        "country_gid": "whosonfirst:country:85632997",
        "country_a": "BEL",
        "macroregion": "Vlaams Gewest",
        "macroregion_gid": "whosonfirst:macroregion:404227357",
        "region": "Antwerpen",
        "region_gid": "whosonfirst:region:85681715",
        "county": "Antwerpen",
        "county_gid": "whosonfirst:county:102050005",
        "locality": "Bergen",
        "locality_gid": "whosonfirst:locality:101755783",
        "label": "49 Heidedreef, Bergen, Belgium"
      }

**Comment by nvkelso** [comment]
@stepps00 Please work with Search team to debug this issue & propose fix.

**Comment by stepps00** [comment]
Best method to finding instances of neighborhoods in Belgium with this same problem (neighborhoods listed as localites), would be to [query in GitHub](https://github.com/whosonfirst/whosonfirst-data/search?utf8=%E2%9C%93&q=%22\%22wof%3Aplacetype\%22%3A\%22locality\%22%22+%22\%22wof%3Acountry%3A+\%22BE\%22%22+%22suburbs+point-in-poly%E2%80%9D&type=Code) all records with: 
* `wof:placetype` of `locality`
* `wof:country` of `BE`
* `qs:type` of `suburbs point-in-poly`

Once this list is compiled, the `wof:placetype` would be changed from `locality` to `neighborhood`. After sanity checking this new dataset, import to Master. @dianashk and I reviewed a few records using this query and it looks like a valid approach.

**Comment by nvkelso** [comment]
Looks like we imported WOF `localities` from Quattroshapes, there was no open GIS data for Belgian **municipalities** at the time. 

1. Is there good open GIS for Belgian **municipalities** now?
2. If there is, that should probably go into the WOF `localadmin` slot to match other countries. 
3. Or we replace localities with the new municipalities. Which is a lot of untangling.

**Comment by nvkelso** [comment]
Alternatively, we one-off fix the bogus locality by merging it into it's neighbour. But worth a little research to fix this across the entire country 1st.

**Comment by stepps00** [comment]
After review, it seems this issue is not due to `neighourhood` records being listed as `localities`, but rather `localadmin` data missing from our WOF records in Belgium. There are [589 municipalities](https://en.wikipedia.org/wiki/Municipalities_of_Belgium) in Belgium, which would fit into the WOF hierarchy as `localadmin` records. These 589 records are split roughly in half, with data for the Northern 308 municipalities being available by the [Flemish government under a Free Open Data License 1.0](http://www.geopunt.be/download?container=referentiebestand-gemeenten&title=Voorlopig%20referentiebestand%20gemeentegrenzen).' However, the Southern half (and Brussels)  areas do not currently have an open data license for municipal data. 

Instead of modifying the current `neighbourhood` or `locality` data in Belgium, the best approach is likely to import new `localadmin` records for the Northern areas of Belgium. This would return "Schilde" for the user's search results, as their location is within the new geometry of Schilde.

**Comment by stepps00** [comment]
S3 WOF bucket now contains `localadmin` records for northern (Flemmish) region.

**Comment by Platzii** [comment]
Any updates on this?

**Comment by nvkelso** [comment]
We lost track of this, I'm very sorry!

We are starting to have a better process for merging fixes like this, hope to fix it for you this month. Thanks for your patience.

**Comment by Platzii** [comment]
Okay, thanks!

---
FYI:

Open data Brussels Capital Region: http://bric.brussels/en/our-solutions/urbis-solutions/urbis-data/urbis-adm
- Technical info (dutch): http://cibg.brussels/nl/onze-oplossingen/urbis-solutions/bestanden/urbis-adm.pdf
- Open data license (dutch): http://cibg.brussels/nl/onze-oplossingen/urbis-solutions/urbis-open-data-licentie
- Direct link: https://s.irisnet.be/v1/AUTH_ce3f7c74-fbd7-4b46-8d85-53d10d86904f/UrbAdm/UrbAdm_SHP.zip

**Comment by nvkelso** [comment]
@stepps00 Can you look at the additional Brussels data, please? Then make a PR for the old S3 data and any new data.

**Comment by stepps00** [comment]
Note: `postalcode` record updates are being tracked in https://github.com/whosonfirst-data/whosonfirst-data-postalcode-be/pull/1.
