### ISSUE TITLE
Indicate which geometry alt should be used for reverse geocoding

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#367]
(updated) We should indicate to Point in Polygon (reverse geo) services which of the multiple geometry alts to use as the default geometry is not always the best to use.

In the following example we should use Quattroshapes geometries by defaul, instead of NaturalEarth geometries (this is true for several records). As seen in Canada (below), this caused the descendants of Sumas, WA to be given a hierarchy that contained Canada.

<img width="1175" alt="screen shot 2016-07-11 at 6 13 34 pm" src="https://cloud.githubusercontent.com/assets/18567700/16752094/74a154f0-4793-11e6-8a53-072f1d5c91f3.png">

This is due to the NaturalEarth shapes overlapping international borders (Canada overlapping the US shown below):

<img width="1187" alt="screen shot 2016-07-11 at 6 16 29 pm" src="https://cloud.githubusercontent.com/assets/18567700/16752104/9dd8cea2-4793-11e6-8a38-6b2b6a4b5c37.png">

We should add a new property that specifies which alt-shape to use with PIP service.

**Comment by nvkelso** [comment]
I've updated the title to reflect the data model change. 

@dianashk, @trescube, and @thisisaaronland for PIP reverse geo service implications.

**Comment by nvkelso** [comment]
I propose this new property go in the src property block like so:

`src:rev_geo` = `quattroshapes`

**Comment by nvkelso** [comment]
@thisisaaronland there are a bunch of WOF venues that will need reprocessing, and this faulty PIP results will also affect OSM record decoration in Pelias until it's fixed.

**Comment by nvkelso** [comment]
We'll need to backfill this for `country` place types only at first.

**Comment by nvkelso** [comment]
Here's a white boarding session from last week:

![img_1580](https://cloud.githubusercontent.com/assets/853051/17260566/0866dac0-5586-11e6-9ca0-a3e74442ce1b.JPG)

Even without all that moving around, I think it'd be pretty easy to take the ~10 countries with `ne` sourced geometries and set a new `revgeo` property to `qs` for now to unblock Pelias. It's just a question of what namespace to put it in? Loose in the top-level property or under wof or in a new `geometry` section in properties (unless that's confusing with the geometry object sibling to properties in GeoJSON)?

**Comment by nvkelso** [comment]
Related, generating "display" geometries at 640, 2048, and 4096 resolutions: https://github.com/whosonfirst-data/whosonfirst-data/issues/131

**Comment by thisisaaronland** [comment]
How is this related? I mean I understand that they're related by the pointers but one issue is about the pointers and the other is about actually generating files.

**Comment by nvkelso** [comment]
Making this the forward original (sorry @nvkelso) of https://github.com/whosonfirst-data/whosonfirst-data/issues/224.

and here's @thisisaaronland [relevant comment](https://github.com/whosonfirst-data/whosonfirst-data/issues/224#issuecomment-195761295) copied here: 

```
I would like to propose that we categorize reverse-geocoding by level. Specifically:

level 0 (default) - land-masses; basically places where fish would die, 
notwithstanding lakes and rivers and the like.

level 1 - land-masses but inclusive of coastal areas; places where 
fishermen in newfoundland would petition the federal government to 
seize the fishing trawlers of countries like portugal and japan; the so-called 
"200 mile" limit for some definition of "200 miles"

And so on. Honestly we can (and should) stop there for the time being. The
 notion of levels would allow for things like the Alphashapes and the notion 
of reverse-geocoding at something rather than in it. But that is tomorrow's problem.

All of which is to say, this is what the mz: namespace is for. So mz:reversegeo and 
perhaps mz:reversegeo#1 if necessary ?

I'd like to think about fragment identifiers in keys/machinetags but at a glance 
nothing seems overly problematic about the idea...
```

**Comment by nvkelso** [comment]
@thisisaaronland Regarding https://github.com/whosonfirst-data/whosonfirst-data/issues/367#issuecomment-240878757, exactly that & making related issues easier to find.

**Comment by nvkelso** [comment]
Copying over discussion from a few other issues into this main issue.

Template:

- `id-alt-source-use-scope-detail.geojson`

Where: 

- _**source**_ (eg: `uscensus`), **common** – this is the raw original geom from the source
- _**use**_ is intended (e.g.: `display`), **common-optional** – why would this be in the filename, should it instead be a property in the master record pointing at one of these geom alt files?
- _**scope**_ is level-of-scope (e.g.: `terrestrial`), **optional**
- _**detail**_ is the level-of-detail (e.g.: `zoom10` or `1025px`), **optional**

All together: 

- `85668127-alt-uscensus-display-terrestrial-zoom10.geojson`

And in the master record:

- `"src:geom_alt":[ "uscensus-display-terrestrial-zoom10"],`

Permutations:

- `85668127-alt-uscensus.geojson` (common)
- `85668127-alt-uscensus-display.geojson` (common-optional)
- `85668127-alt-uscensus-display-terrestrial.geojson` (optional)
- `85668127-alt-uscensus-display-zoom10.geojson` (optional)
- `85668127-alt-uscensus-display-1024px.geojson` (optional)
- `85668127-alt-uscensus-display-terrestrial-zoom10.geojson` (optional)
- `85668127-alt-uscensus-display-terrestrial-1024px.geojson` (optional)

From https://github.com/whosonfirst-data/whosonfirst-data/issues/538#issuecomment-263814171:

Since I can't find a goal list for Who's On First geometries, here's my list.

- **search** for place by text (free or structured, e.g. forward geocoding) and getting back a (label) lat-long, (label) bounding box, full geometry, and hints about "hierarchy label" generation. 
- **reverse geocode** of lat-long to a place (preferring the "biggest" shape inclusive of territorial waters)
- **data visualization** (map **display**) based on polygon features (e.g. choropleth, with some sophistication around water and land parts, preferring the land parts)
- **label basemap** "points" (e.g.: `locality` townspots + text) and "polygons" (e.g.: `region` area text). It's important to know which "locality" features `do not usually represent a single compact populated place` so their `mz:min_zoom` can be properly set, and we can choose the correct "point" or "polygon" labeling (and possibly switch between them at different zooms)
- **showing boundary lines on a basemap** (e.g. `region` boundary, `disputed` area boundaries, with some sophistication around water and land parts – e.g. option to not show territorial water parts, coastline parts, and/or inland water parts).

**Use:** I think the above goals map to:

- display - if we've optimized it for display
- search - if we've optimized it for reverse geocoding

From https://github.com/whosonfirst-data/whosonfirst-data/pull/539:

**Scope** (geometry clipping is one of):

- `territorial` - default optimized for revGeo inclusive of all marine and territorial waters (no water clipping), understood that Mapzen may have modified the original, but it's still "sourced" to the source.
- `terrestrial` - clipped to land + terrestrial waters (e.g. clipped to ocean coastline, but not punched thru for large inland water bodies), understood that Mapzen may have modified the original, but it's still "sourced" to the source. Used for most choropleth maps.
- `land` - no marine waters, no inland waters. Used in contexts where someone doesn't want to load separate "earth" base or "water" top layers. This matches Tilezen's kind value (terrestrial is more the general catch all for the Tilezen layer). The computed label position should be based on this geometry, when available.
- `marine` - geometric opposite of terrestrial, useful for boundary lines.

Here's table converting 1:x representative fractions (eg: `1:500k`) into web map zooms ([src](http://kelsocartography.com/blog/?p=2407)), with some integer rounding:

![scales_table](https://cloud.githubusercontent.com/assets/853051/20766341/f17fb54a-b6ea-11e6-8432-7d1099b1f341.png)

**Comment by thisisaaronland** [comment]
These details should go over here:

https://github.com/whosonfirst/whosonfirst-cookbook/blob/master/how_to/creating_alt_geometries.md

Again, per the last issue anything besides `source` and `function` (described above as `use`) is left as an arbitrary list of `extras` specific to the alt geometry.

**Comment by nvkelso** [comment]
Fixed ~~use~~ to `function` above. There's some delta between my comment above and what's drafted in the cookbook for @stepps00 to work flag and for us to discuss still. But it feels like we're almost there!

**Comment by stepps00** [comment]
[This commit](https://github.com/whosonfirst/whosonfirst-cookbook/commit/052afff81f464f8917e5683022190c80e432e1a8) updated the `whosonfirst-cookbook` file that outlines alt-geometries. The file should include comments (with some minor edits and formatting) from @nvkelso.

**Comment by nvkelso** [comment]
Related: #548.

**Comment by stepps00** [comment]
For now, use Russia as a test case. 
Set new `reversegeo` coordinate properties using the current `lbl:latitude` and `lbl:longitude` properties for any administrative areas. Place Russia's point over Moscow.

**Comment by nvkelso** [comment]
The property name should be:

- **`reversegeo:polygon`**: `file-name-here`
    where if the filename is `id-alt-source-stuff.geojson` we only store `source-stuff`.

For `wof:placetype` = `country`

- `quattroshapes` only when it's set as `src:geom_alt` and there exists an alt file with that src name.

For all other place types skip. The rest can be dealt with by convention, and we don't need to 2x the size of the repo unnecessarily when the default geom is fine.

In the future once https://github.com/whosonfirst-data/whosonfirst-data/issues/548 lands for the 24 mile nautical limit those new geoms would be added as alts, and we'd point the **`reversegeo:polygon`** property to those new alt geoms.

(Maybe it's useful someday to do this for regions, too, but someday.)

**Comment by nvkelso** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1793
