### ISSUE TITLE
Upgrade Seattle neighbourhoods based on city clerk shapes

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#381]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [x] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by ZBSingleton** [comment]
All final Seattle geojsons included in compressed file below.

[Seattle_Final_20160729.zip](https://github.com/whosonfirst/whosonfirst-data/files/391611/Seattle_Final_20160729.zip)




**seattle_deprecated.geojson**
* Deprecated WOF polygon records. Superseded by feature located in "wof:superseded_by" field.  If field does not contain an ID, feature was dropped due to absence of verifiable data.

**seattle_deprecated_points.geojson**
* Deprecated WOF point records. Superseded by feature located in "wof:superseded_by" field. If field does not contain an ID, feature was dropped due to absence of verifiable data.

**seattle_macrohoods.geojson**
* Collection of Seattle macrohoods. Features supersede original neighborhoods by the same name in WOF records.

**seattle_microhoods.geojson**
* Collection of Seattle microhoods. Features supersede original neighborhoods by the same name in WOF records. Features with no recorded ID in the "wof:supersedes" field are new and do not correspond to an existing WOF record.

**seattle_no_wof.geojson**
* Collection of neighborhoods in Seattle compiled from source/outside information. No WOF record exists that it could be matched to. If "seagv:" fields are blank, information was obtained from a source not affiliated with the Seattle city government GIS program.

**seattle_waterways.geojson**
* Collection of neighborhoods representing major waterways throughout the Seattle area. These waterways abut a number of marinas in the area.

**seattle_water_macro.geojson**
* Groupings for the major waterways (placetype 'neighborhood') in Seattle. Each of these features parents one found in the seattle_waterways geojson.

**seattle_water_micro.geojson**
* Collection of microhoods (marinas) scattered throughout Seattle. These are the land-based components of the marina and do not include docks/wharves for landmass parenting purposes.

**seattle_water_micro_alt.geojson**
* Alternate geometries for the features found in the seattle_water_micro geojson. These geometries include both land and water-based components of the marinas.

**seattle_wof.geojson**
* Collection of neighborhoods in Seattle compiled from source/outside information with existing WOF record. If "seagv:" fields are blank, information was obtained from a source not affiliated with the Seattle city government GIS program.



**Compiled Geomtries**
![seattle](https://cloud.githubusercontent.com/assets/20478541/17266877/c5133840-55b2-11e6-8bbe-2b3aa1002896.PNG)
Above are displayed all microhoods, neighborhoods, and macrohoods layered on top of one another. The microhoods are represented by polygons filled with diagonal lines, the neighborhoods by a simple green fill, and the different macrohoods by a grouping of adjacent polygons with a similar (off-color) fill.

**Sourcing Information**
* Open source data license

* [Seattle Source](https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/seagv.json)

**Comment by nvkelso** [comment]
@stepps00 Please verify Seattle is ready for import, then assign to Aaron.

**Comment by ZBSingleton** [comment]
Corrected minor geometry error for Stimson Bay Marina in seattle_water_micro.geojson. Re-uploaded file in original data comment for thread.

**Comment by stepps00** [comment]
Files look great! Over to @thisisaaronland.  

Seattle [files](https://s3.amazonaws.com/whosonfirst.mapzen.com/misc/Issue%20381/Seattle_Import_Files.zip) for import are now in the S3 misc/Issue 381 folder.

**Comment by nvkelso** [comment]
I still need to review the `min_zoom` and `max_zoom` properties on the revised and new records.

**Comment by ZBSingleton** [comment]
Corrected and re-uploaded Seattle files in original comment with proper data formatting (array values where applicable), missing fields (lbl:latitude/longitude, wof:country, etc.), and valid geometries (correction for minor rendering issue).

**Comment by stepps00** [comment]
Seattle neighbourhood work is complete, closing issue.
