### ISSUE TITLE
Upgrade neighbourhood shapes for Montreal

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#418]
### tl;dr

Status:
- [x] Propose **sources**
- [x] Establish **concordances** between WOF and source
- [x] **Upgrade / add** WOF shapes
- [x] **Add new or missing** features to WOF
- [x] **Deprecate / supersede** WOF features
- [x] **Draft review**
- [x] **Draft revisions** based on review comments
- [x] **Final review**
- [x] **Final revisions** based on review comments
- [ ] **Import** into Who's On First
### Details

Sourcing:
- Permissive license?
- Add new src to Who's On First

Upgrade / add:
- `macrohood`
- `neighbourhood`
- `microhood`

Add new or missing features to WOF
- `macrohood`
- `neighbourhood`
- `microhood`

Deprecate / supersede:
- `macrohood`
- `neighbourhood`
- `microhood`

**Comment by nvkelso** [comment]
**Possible references:**

- https://en.wikipedia.org/wiki/List_of_neighbourhoods_in_Montreal
- https://www.google.com/maps/d/u/0/viewer?mid=zEVTt9jibRyA.k-xfSW0m0XeA&hl=en 
- http://www2.ville.montreal.qc.ca/arrondissements/sla/historique/en/intro/histvsl/terri/quartdev/quartdev.html


NOTES:

1. Sourcing usable neighborhoods data is a challenge as Montreal is bilingual, but the more detailed stuff is mostly in French. 
2. There has been enough dramatic rearrangement (2002 and 2006 the cities went through a massive consolidation and then deconsolidation) that it's hard to know what data comes from what iteration of official neighborhoods.

**Comment by stepps00** [comment]
Related: #132

**Comment by stepps00** [comment]
Files are now in S3, in the `misc`/`Issue 418` folder.

**Comment by stepps00** [comment]
For post-merge clean-up: [montreal_hierarchies.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1030261/montreal_hierarchies.txt)

**Comment by stepps00** [comment]
@thisisaaronland - Assigning this issue as one of the two neighbourhood issues for manual import.

**Comment by thisisaaronland** [comment]
What is the rationale for making the river (Fleuve St. Laurent) a "neighbourhood" in Montreal?

I am not opposed to it but it's sufficiently weird that it should be articulated somewhere that we can point people to. It should probably also be coterminous with the record for the river itself which is what people think of when you talk about "the river" (as in the whole thing).

**Comment by stepps00** [comment]
We've generally been updating neighbourhood records to include any area within the locality geometry so we have a full coverage at that placetype, with some caveats. For areas like Fleuve St. Laurent or large parks/open areas, we've created a neighbourhood record, but used the `"mz:is_landuse_aoi:1"` tag. Past examples: [Willamette River](https://whosonfirst.mapzen.com/spelunker/id/1108721301/#10/45.5530/-122.7273) and [Lake Union](https://whosonfirst.mapzen.com/spelunker/id/890537407/#13/47.6399/-122.3358).

I've opened https://github.com/whosonfirst-data/whosonfirst-data/issues/800 to track updating `marinearea` records in WOF so that placetype is consistent with our admin records we're updating. This would probably include some `wof:coterminous` work.

Agree that we should document this somewhere - would this be best documented in the placetypes repo or cookbook repo (or another)?
