### ISSUE TITLE
Newbury localadmin has geometry, locality doesn't

### ISSUE THREAD

**Issue by orangejulius** [whosonfirst-data/whosonfirst-data#430]
Take a look at https://whosonfirst.mapzen.com/spelunker/id/101852663/#13/51.3992/-1.3203

That link goes to the `locality` record for Newbury, UK. That record itself has no geometry (it's a buffered point from Quattroshapes). However, the `localadmin` record for Newbury has what looks like a very nice geometry.

I suspect in this case, the geometries of the two records should actually be identical, so maybe the geometry can just be reused. If so great, if that's not correct, or there's a better solution, that's fine too.

However, this got me thinking about the larger issue. Might there be a lot of places where the `localadmin` has a reasonable geometry, and the `locality` has no geometry? If so, is there a general solution WOF could implement? If not, perhaps Pelias will make the decision to "copy" the geometry from the `localadmin` to `locality` in cases like this. Is that a reasonable idea?

**Comment by stepps00** [comment]
Suggest that we close this issue, as we have a similar issue (#234) open.

The `locality` record for Newbury, UK does have a geometry, but that geometry is in the shape of an ellipse. As suggested in #234, the best option may be to add logic to Pelias to use `localadmin` geometries when a locality's `qs:type = buffered point`.

**Comment by nvkelso** [comment]
If the two records are in fact [coterminous](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#coterminous), then they should be marked that way in the `wof` properties section. (That's probably the case here but I'd need to research it more, it's fine to link them up now to establish test data.)

If **Pelias** sees that a feature is `coterminous` with another and it's own geometry is approximate, but the coterminous's geometry is not, then I think it'd be okay to use the coterminous feature's geometry. (But not much of that is wired up in the Who's On First data, yet.)

Let's keep this issue open (versus marking it a dup of https://github.com/whosonfirst-data/whosonfirst-data/issues/234), as UK data is more fixable than that in Ireland (which is the general approximate case) because we do have those UK `localadmin` shapes to work from.

@orangejulius Is the UK locality data a huge priority to fix, or is a medium term fix okay? (It's more than a day's worth of work, might be a couple weeks.)

**Comment by orangejulius** [comment]
Thanks @nvkelso, that's exactly the interpretation I was looking for. It definitely feels like this case is different than the one in #234 since the geometries are probably coterminous. (in #234, there was no `localadmin` record). Pelias will talk about using the `localadmin` geometry for admin lookup in this case, since it seems to make sense.

As for priority, other than @zerebubuth living nearby, In general I don't think you have to rush any changes in, I was more curious about the issue in general.

**Comment by zerebubuth** [comment]
I think this came up as a "huh... wait, what?" moment when @souperneon and I were beta-testing ODES. Not a high priority to fix, other than that it's being shown in the ODES GUI and might cause some confusion.

**Comment by stepps00** [comment]
The following commands yield 648 `buffered point` features in GB:
```
find /usr/local/mapzen/whosonfirst-data/data -type f -exec grep -l 
'"qs:type":"buffered point",' {} + | xargs grep  '"iso:country":"GB",' > grep.csv
```
I'll work through these (and the parents) to add `coterminous` properties

**Comment by nvkelso** [comment]
Looks like PR needs updating, and it's for a nearer term rainy day.

**Comment by souperneon** [comment]
get 'er done!

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1367#issuecomment-435144511

**Comment by stepps00** [comment]
**locality**: https://github.com/whosonfirst-data/whosonfirst-data/blob/stepps00/uk-localities/data/101/852/663/101852663.geojson

**localadmin**: https://github.com/whosonfirst-data/whosonfirst-data/blob/stepps00/uk-localities/data/404/449/013/404449013.geojson

In this branch, both records have polygon geometries and are flagged as coterminous with one another.

**Comment by stepps00** [comment]
**locality**: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/101/852/663/101852663.geojson

**localadmin**: https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/404/449/013/404449013.geojson

Localities in the UK now have polygons, including Newbury. Closing issue.

**Comment by orangejulius** [comment]
:clap: This is great, thanks.
