### ISSUE TITLE
GADM

### ISSUE THREAD

**Issue by jharpster** [whosonfirst-data/whosonfirst-data#48]
Would be great to import the latest 2.5 version of GADM boundaries. http://www.gadm.org/

**Comment by smesdaghi** [comment]
The county coverage of GADM is impressive and if importing GADM polygons is an option, it would be great to see all the missing counties added as well. Are there any licensing issues that would prevent this?

**Comment by stepps00** [comment]
Hey @jharpster and @smesdaghi - thanks for the issue and question regarding import of the county data! Unfortunately, there are licensing issues that prevent us from importing the GADM county boundaries wholesale, _but_ we do have new county features on the way.

We are in the process of filling in county coverage gaps; soon, we will have new county features in Who's On First for 87 countries. These features can be tracked in our [open pull requests](https://github.com/whosonfirst-data/whosonfirst-data/pulls) (tagged with `meso`), if needed.

Thanks again and I'll update this issue once things progress with the county features.

**Comment by stepps00** [comment]
Hey, @jharpster and @smesdaghi - I wanted to let you know that we've recently imported new `admin2` (county) level features for over 100 countries into Who's On First. If you'd like more info about the data or process, we've blogged about the new import [here](https://mapzen.com/blog/mesoshapes/). In addition, we're planning to import new `admin1` (region) level data into Who's On First in the coming month.

I'm going to close this issue because, unfortunately, we can't import the GADM data wholesale. Thanks for opening the issue, though, and enjoy the data!
