### ISSUE TITLE
Nashville label appears to be incorrect

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#482]
The record for [Nashville](https://whosonfirst.mapzen.com/spelunker/id/101723183/#10/36.1869/-86.7852), TN has the value for `wof:name` of "Nashville" but it's `wof:label` value is "Nashville-Davidson County".  Is this correct?

**Comment by stepps00** [comment]
Hmm, this is _not_ correct. I thought this issue had to do with an import from https://github.com/whosonfirst-data/whosonfirst-data/issues/217, but that doesn't seem to be the case.

I'll investigate, update the Nashville record, and crawl through other records with `wof:label` fields to ensure they are correct.

**Comment by stepps00** [comment]
Looks like the `wof:label` field was added to the locality record, instead of the county record in [this](https://github.com/whosonfirst-data/whosonfirst-data/pull/264) merged PR.

New PR opened to revert the change (https://github.com/whosonfirst-data/whosonfirst-data/pull/483).

Also, #217 is open and waiting for merge, which will add the `wof:label` field to the actual county record.
