### ISSUE TITLE
Update records in disputed areas of India

### ISSUE THREAD

**Issue by tallytalwar** [whosonfirst-data/whosonfirst-data#496]
These might result in a bunch of issues, not sure in what category each falls in. Hence a single issue.
- [x] "Andaman and Nicobar", "Lakshadweep" and "Daman and Dui" are marked as disputed in WOF:
   https://whosonfirst.mapzen.com/spelunker/id/85672175/#6/10.232/93.254
   https://whosonfirst.mapzen.com/spelunker/id/85632275/#7/9.987/72.897
   https://whosonfirst.mapzen.com/spelunker/id/85672271/#9/20.5581/71.9278
   
   But I do not see these in "All Descendants of India with placeType = disputed": https://whosonfirst.mapzen.com/spelunker/id/85632469/descendants/?exclude=nullisland&placetype=disputed#5/32.193/79.121
   
   Also both these set of islands are not disputed and are not claimed by any other nation, other than India.
   Refer: [this](http://cdn.static-economist.com/sites/default/files/imagecache/full-width/images/2014/04/blogs/banyan/himalayan_201034fbc949.gif) and [this](https://en.wikipedia.org/wiki/List_of_disputed_territories_of_India).
- [x] I see this "India" https://whosonfirst.mapzen.com/spelunker/id/85632701/#7/28.125/94.479 in the list of descendants of India, with placetype disputed. But this is actually be https://whosonfirst.mapzen.com/spelunker/id/85672259/#7/28.017/94.468
- [x] What is the difference between the 2 "Jammu and Kashmir" here:
   https://whosonfirst.mapzen.com/spelunker/id/85632427/#7/33.922/76.528
   https://whosonfirst.mapzen.com/spelunker/id/85672137/#7/33.913/76.640
   And when consolidating a list of disputed regions which one should be considered.
- [x] https://whosonfirst.mapzen.com/spelunker/id/85675745/#7/35.786/74.782 region should be marked disputed with India.

**Comment by stepps00** [comment]
@tallytalwar - thanks for filing the issue! Here are some answers/comments to your points:

>"Andaman and Nicobar" and "Lakshadweep" are marked as disputed in WOF:
    https://whosonfirst.mapzen.com/spelunker/id/85672175/#6/10.232/93.254
    https://whosonfirst.mapzen.com/spelunker/id/85632275/#7/9.987/72.897

>    But I do not see these in "All Descendants of India with placeType = disputed":     https://whosonfirst.mapzen.com/spelunker/id/85632469/descendants/?exclude=nullisland&placetype=disputed#5/32.193/79.121

>    Also both these set of islands are not disputed and are not claimed by any other nation, other than India.
    Refer: this and this.

The record for [Lakshadweep](https://whosonfirst.mapzen.com/spelunker/id/85632275/#7/9.996/72.889) is a `region` record in India with the correct hierarchy and belongsto information, but has the following incorrect property values:

````
"iso:country":"XX",
"wof:country":"XX",
````

This record (correctly) does not appear in the [disputed descendant records](https://whosonfirst.mapzen.com/spelunker/id/85632469/descendants/?exclude=nullisland&placetype=disputed#5/32.193/79.121) in India. However, those country codes above do need to be edited.

Conversely, the record for [Andaman and Nicobar](https://whosonfirst.mapzen.com/spelunker/id/85672175/#6/10.239/93.241) is a `region` record in India that has a disputed hierarchy (below), but has correct country codes.

````
    "wof:hierarchy":[
        {
            "country_id":85632469,
            "disputed_id":85632701,
            "region_id":85672175
        },
        {
            "country_id":85632695,
            "disputed_id":85632701,
            "region_id":85672175
        }
    ],
````

This record also (correctly) does not appear in the [disputed descendant records](https://whosonfirst.mapzen.com/spelunker/id/85632469/descendants/?exclude=nullisland&placetype=disputed#5/32.193/79.121) in India. However, the portion of the hierarchy containing China needs to be removed.

>I see this "India" https://whosonfirst.mapzen.com/spelunker/id/85632701/#7/28.125/94.479 in the list of descendants of India, with placetype disputed. But this is actually be https://whosonfirst.mapzen.com/spelunker/id/85672259/#7/28.017/94.468

That's correct - [this India record](https://whosonfirst.mapzen.com/spelunker/id/85632701/#7/28.125/94.479) actually represents the disputed region of Arunachal Pradesh, but we also have that [region record for Arunachal Pradesh](https://whosonfirst.mapzen.com/spelunker/id/85672259/#7/28.017/94.468). The former is in the hierarchy of the latter.

What likely needs to happen here: deprecate the "India" record because it is incorrect and update the hierarchies of its descendants.

>What is the difference between the 2 "Jammu and Kashmir" here:
    https://whosonfirst.mapzen.com/spelunker/id/85632427/#7/33.922/76.528
    https://whosonfirst.mapzen.com/spelunker/id/85672137/#7/33.913/76.640


Similar to the Arunachal Pradesh record above, we have a `disputed` record and a `region` record for Jammu and Kashmir - the `disputed` record should be kept and the `region` record should be deprecated.

 >And when consolidating a list of disputed regions which one should be considered.

The `wof:placetype` property should be used to consolidate the list of disputed regions - with the example of Arunachal Pradesh, we have one record with a `region` placetype and one record with a `disputed` placetype. You'll want that `disputed` record, not the `region` record.

Last thing - we're actually [importing](https://github.com/whosonfirst-data/whosonfirst-data/pulls) all new `county` features (and other placetypes), so all of these records in India will be updated soon.

**Comment by tallytalwar** [comment]
Thanks @stepps00. All the answers make sense to me. Should I create individual issues for these or these will be done under the "importing" all new county feature work?

I added another to the list in the description. This is similar to Andaman/Lakshadweep:
https://whosonfirst.mapzen.com/spelunker/id/85672271/#9/20.5581/71.9278

Again this, "Daman and Dui" should not be a disputed territory.

**Comment by stepps00** [comment]
For now, let's go ahead and leave everything in one issue - I'll rename it "Update records in disputed areas of India."

The new imports won't directly correct this issue, but the resulting geometries will _probably_ be used to update the records we've linked above.. I'll work on a PR to correct this issue before the import, in case we can fix these issues sooner rather than later.

Thanks again and keep appending any "disputed area" issues to the original issue comment.

**Comment by stepps00** [comment]
Noting existing issues that provide more info on 

[1](https://github.com/whosonfirst-data/whosonfirst-data/issues/169) and [2](https://github.com/whosonfirst-data/whosonfirst-data/issues/170).

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/636

**Comment by nvkelso** [comment]
Some of this is done, some may remain.

**Comment by nvkelso** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/1341 should resolve all the problems itemized in the description.

**Comment by stepps00** [comment]
Thanks for the help with this one, @tallytalwar
