### ISSUE TITLE
Duplicate Lancaster, PA localadmin records

### ISSUE THREAD

**Issue by dianashk** [whosonfirst-data/whosonfirst-data#499]
Came across these two when doing some deduplication testing in Pelias.

https://whosonfirst.mapzen.com/spelunker/id/404487183/#12/40.0399/-76.3000
https://whosonfirst.mapzen.com/spelunker/id/404482867/#12/40.8521/-80.1115

One clearly has better geometry, but not sure why the other exists as well. Should it get a superseded_by tag?

**Comment by stepps00** [comment]
At first glance, these look like two duplicate records, but they're actually two records representing two distinct "Lancaster" features.

https://whosonfirst.mapzen.com/spelunker/id/404487183/#12/40.0399/-76.3000
This is the `localadmin` record of Lancaster in Lancaster County, PA.

https://whosonfirst.mapzen.com/spelunker/id/404482867/#12/40.8521/-80.1115
This is the `localadmin` for Lancaster Township in Butler County, PA. Sources:

* https://en.wikipedia.org/wiki/Lancaster_Township,_Butler_County,_Pennsylvania
* http://www.lancaster-township.com/

Since the `wof:name` field shouldn't include "Township," I could add a `wof:label` field to the record, but I'm not sure if that would be helpful.

EIther way, thanks for the issue!

**Comment by stepps00** [comment]
Closing - no actionable item.
