### ISSUE TITLE
"hasc" concordances need to be "hasc:id"

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst-data/whosonfirst-data#515]
This should wait until after all the mesoshapes have been merged in.

**Comment by nvkelso** [comment]
What's the proposed before and after?

`concordance: { 'hasc': 'xxx' }`
versus
`concordance: { 'hasc:id': 'xxx' }`

**Comment by thisisaaronland** [comment]
Yes, concordances need a prefix (`hasc`) and ID reference (`id` or `code` or whatever)

**Comment by stepps00** [comment]
This issue was taken care of via https://github.com/whosonfirst-data/whosonfirst-data/commit/02831853557f2734e0a49b7be70790a8fb43037b

Additional `hasc` concordance work is being tracked in #479 (PR: https://github.com/whosonfirst-data/whosonfirst-data/pull/869).

I'm going to close this issue since there is nothing actionable here.
