### ISSUE TITLE
There should only be one Brcko District in BA

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst-data/whosonfirst-data#63]
One of these is likely bunk:

Brcko Distrikt  29389649    1104089 Brčko Distrikt quattroshapes   1439838188      85632279    BA
Bosnia and Herzegovina  0   224784  Brcko Distrikt  quattroshapes   1439838982      85632609    BA

**Comment by hugovk** [comment]
First one looks correct:
https://github.com/whosonfirst/whosonfirst-data/blob/master/data/856/322/79/85632279.geojson
Second one is the country, Bosnia and Herzegovina:
https://github.com/whosonfirst/whosonfirst-data/blob/master/data/856/326/09/85632609.geojson

**Comment by stepps00** [comment]
@nvkelso - Original list includes country and region, instead of these two regions:

* https://whosonfirst.mapzen.com/spelunker/id/85632279/
* https://whosonfirst.mapzen.com/spelunker/id/85669257/

Suggest deprecating `85669257` since it has more property fields and concordances, moving its properties to `85632279`, and retaining the geometry.

**Comment by stepps00** [comment]
This issue was taken care of in https://github.com/whosonfirst-data/whosonfirst-data/commit/5fce59f5d01752f2e0317c45e85bdc6e0926dae9. Will close the issue once this commit is pushed to `master`.

**Comment by stepps00** [comment]
5fce59f was merged to master, closing issue.

https://whosonfirst.mapzen.com/spelunker/id/85632279/ now supersedes https://whosonfirst.mapzen.com/spelunker/id/85669257/.
