### ISSUE TITLE
Investigate and fix and/or add alternate spelling for UAE emirates

### ISSUE THREAD

**Issue by IndyHurt** [whosonfirst-data/whosonfirst-data#64]
The official UAE government portal has Abu Dhabi, Dubai, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah and Fujairah.

The CIA World Factbook has a slightly different variation with alternates:
https://www.cia.gov/library/publications/the-world-factbook/fields/2051.html#ae

**Comment by stepps00** [comment]
It looks like this issue was taken care of with the recent wikipedia name import. Suggest we close this issue, as all `wof:name` fields and `eng_x` fields contain all names for UAE regions.

**Names as listed on the cia.gov:**

* _Abu Zaby (Abu Dhabi)_
* _'Ajman_
* _Al Fujayrah_
* _Ash Shariqah (Sharjah)_
* _Dubayy (Dubai)_
* _Ra's al Khaymah_
* _Umm al Qaywayn_

**Names in Who's On First:**

* _Abu Zaby (Abu Dhabi)_
```
    "name:eng_x_variant":[
        "Abu Zaby"
    ],
```

* _'Ajman_
```
    "name:eng_x_variant":[
        "`Ajman"
    ],
```

* _Al Fujayrah_
```
    "name:eng_x_preferred":[
        "Fujairah"
    ],
    "name:eng_x_variant":[
        "Al Fujayrah"
    ],
```

* _Ash Shariqah (Sharjah)_
```
    "name:eng_x_preferred":[
        "Sharjah"
    ],
    "name:eng_x_variant":[
        "Ash Shariqah"
    ],
```

* _Dubayy (Dubai)_
```
   "name:eng_x_variant":[
        "Dubayy",
        "Dubay"
    ],
```

* _Ra's al Khaymah_
```
    "name:eng_x_preferred":[
        "Ras al Khaimah"
    ],
    "name:eng_x_variant":[
        "Ra's al Khaymah"
    ],
```

* _Umm al Qaywayn_
```
    "name:eng_x_preferred":[
        "Umm Al Quwain"
    ],
    "name:eng_x_variant":[
        "Umm al Qaywayn"
    ],
```

**Comment by stepps00** [comment]
Verified that these name properties have been updated and each `region` in the UAE has correct `name:eng_x_preferred` property values.

Closing issue.

**Comment by rmglennon** [comment]
Hey @stepps00 - This looks like it brings in regions. For example, Dubai is a region: https://whosonfirst.mapzen.com/spelunker/id/85667983/

What about these locations as localities? This came in through support (see Desk 888) - a user was using Mapzen Search and could not get a result for Dubai when filtering for layer=locality and sources=wof.
