### ISSUE TITLE
places with the name 'City'

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#645]
the following wof records have the name 'City' which, albeit possible, are unlikely the correct name:

```
City|default|101938739
City|default|404516183
City|default|404549959
City|default|420781621
City|default|420782383
City|default|420784611
City|eng|101938739
City|eng|404516183
City|eng|404549959
```

**Comment by stepps00** [comment]
thanks @missinglink - will take a look shortly.

**Comment by stepps00** [comment]
**City|default|101938739**
  - This is the City Center area of Canberra, AUS. 
  - According to [Wikipedia](https://en.wikipedia.org/wiki/Civic,_Australian_Capital_Territory), " its official division name is City." 
  - No changes required.

**City|default|404516183**
  - This is a township in Missouri.
  - [Wikipedia](https://en.wikipedia.org/wiki/City_Township,_Barton_County,_Missouri) confirms the name is "City Township."
  - Since there are no placetype suffixes in the `wof:name`, no changes required.

**City|default|404549959** (see **101938739** above)
  - This is the City Center area of Canberra, AUS. 
  - According to [Wikipedia](https://en.wikipedia.org/wiki/Civic,_Australian_Capital_Territory), " its official division name is City." 
  - No changes required.

**City|default|420781621**
  - This _likely_ represents the "City of London", as its fairly close to the center London's city boundary. I can not find any information online about a "City"neighbourhood in London.
  - London neighbourhood updates are being tracked in issue #411.
  - Suggest either deprecating this record now or waiting for London neighbourhood work to be completed.

**City|default|420782383**
  - This is a district in Zurich.
  - According to sources ([1](https://en.wikipedia.org/wiki/Altstadt_(Z%C3%BCrich)#City), [2](https://www.inyourpocket.com/zurich/Zurichs-districts_71823f)), this is a valid name for an area of Zurich.
  - No changes required.

**City|default|420784611**
  - This _likely_ represents the Indre By area or City Center area of Copenhangen. I can not find any information online about a "City"neighbourhood in Copenhagen.
  - Suggest deprecating this record now.

**Comment by nvkelso** [comment]
I’m fine deprecating 420784611.

For 420781621 there is technically several localities for “London”,
including one for the older “City of London”, so I’d leave it alone until
we get into it with #411.

**Comment by missinglink** [comment]
wow, thanks for looking in to it!

yet another interesting quirk of the world we live in that makes geocoding tricky :)

**Comment by stepps00** [comment]
Confirming that the London 'City' record(s) will be taken care of in #411.
