### ISSUE TITLE
mixed types for wof:hierarchy (string or integer)

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#714]
some records have a mixed bag of types (strings and integers) in the `wof:hierarchy` property.

eg. https://whosonfirst.mapzen.com/data/101/750/367/101750367.geojson

```
    "wof:hierarchy":[
        {
            "continent_id":"102191581",
            "country_id":"85633159",             <-- string
            "localadmin_id":404435563,           <-- integer
            "locality_id":101750367,
            "macroregion_id":404227469,
            "region_id":85684061
        }
    ],
```

**Comment by stepps00** [comment]
@missinglink - thanks for filing the issue! We actually have an issue tracking this issue (https://github.com/whosonfirst-data/whosonfirst-data/issues/450), so I'm going to close this issue as a duplicate.

This issue is something I'd like to tackle once we land various PRs in whosonfirst. Once these features are imported, I plan to ensure all the `wof:hierarchy` values are integers.
