### ISSUE TITLE
-1 hierarchy references

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#730]
hey, what does -1 mean for a `wof:hierarchy`?

could you plz put something in `README.KNOWN.KNOWNS.md` about what that is and how data consumers should deal with it.

I'm assuming it means that Sydney has a `locality` and `region` but we have at some point removed the link for some reason?

https://whosonfirst.mapzen.com/spelunker/id/85771099

```
{
  "wof:hierarchy": [
    {
      "continent_id": 102191583,
      "country_id": 85632793,
      "locality_id": -1,
      "neighbourhood_id": 85771099,
      "region_id": -1
    }
  ]
}
```

**Comment by stepps00** [comment]
hey @missinglink - we have some documentation on the `-1` `wof:parent_id` values in the whosonfirst-properties repo ([here](https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#parent_id)). A negative one value basically means.. "we don't know."

I'll add some of this info to the README in a PR for more clarity.

**Comment by thisisaaronland** [comment]
It follows the same logic as `parent_id`: 

https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#parent_id

The hierarchy is the result of invoking a secondary "ensure hierarchy" function in the event that `parent_id` can not be determined. We _should_ be able to determine both locality and region but can't (because in this case both the label and geom centroids are in the water) and `-1` is a signal that a record needs to be vetted.

Sydney (and AU) are generally a hot mess right now but there is an open ticket to update all the neighbourhoods with official Govt of AU data for all the things.
