### ISSUE TITLE
missing two smaller capital cities

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#738]
heya, I'm working through a list of capital cities I was given and it looks like we are missing a couple of smaller ones:

### Saint Peters Port, Guernsey

- https://en.wikipedia.org/wiki/Saint_Peter_Port
- https://whosonfirst.mapzen.com/spelunker/id/85632547/descendants/?exclude=nullisland#10/49.5702/-2.2147

### Plymouth, Montserrat

- https://en.wikipedia.org/wiki/Plymouth,_Montserrat
- https://whosonfirst.mapzen.com/spelunker/id/85632677/descendants/?exclude=nullisland#12/16.7521/-62.1917
- note: wikipedia says it's an 'Abandoned town'

they're generally small places but would be nice to have for completeness :)

**Comment by nvkelso** [comment]
This lines up with work @stepps00 is engaged with in https://github.com/whosonfirst-data/whosonfirst-data/tree/stepps00/capital_of, please expect a fix for these (and others) "soon".

**Comment by stepps00** [comment]
hey @missinglink - I'm actually in the process of linking all capital cities with their country and vice versa, via https://github.com/whosonfirst-data/whosonfirst-data/issues/57. I've created 17 new locality records for capitals that are missing in Who's On First. You can see these new features in this commit - https://github.com/whosonfirst-data/whosonfirst-data/pull/735/commits/973c17b3438963c145b408fe4e17c711b81037ef.

This will actually not include Plymouth, Monserrat because Who's On First considers Monserrat a `dependency` of the United Kingdom. Because I haven't (and won't) create a Plymouth record for Monserrat for  #57, I'll leave this issue open to add Plymouth. 

Feel free to add other missing dependency capitals if you come across them!

**Comment by missinglink** [comment]
that's all I got! I tested 1403 names of capital cities and large cities internationally (I sourced from an outside contributor) and those were the only ones I couldn't find so generally the quality is very high :)

**Comment by stepps00** [comment]
Note: A record for Saint Peters Port, Guernsey will be created through work for #107.
