### ISSUE TITLE
Review all misc:* properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst-data/whosonfirst-data#826]
Review all `misc:*` properties in records. Some of these `misc:*` properties are actually valid source properties, but the property was imported with a `_` character instead of a `:` character.

An example is the ["Golden Square Mile"](https://whosonfirst.mapzen.com/data/858/664/91/85866491.geojson) record in Montreal. This record includes the following `misc:*` properties:

```
    "misc:gn_adm0_cc":"CA",
    "misc:gn_id":0,
    "misc:gn_local":6077243,
    "misc:local_max":28614,
    "misc:local_sum":313611,
    "misc:localhoods":127,
    "misc:name":"Montreal Golden Square Mile",
    "misc:name_adm0":"Canada",
    "misc:name_adm1":"Qu\u00e9bec",
    "misc:name_adm2":"Montr\u00e9al",
    "misc:name_local":"Montr\u00e9al",
    "misc:photo_max":3049,
    "misc:photo_sum":23285,
    "misc:placetype":"Suburb",
    "misc:quad_count":74,
    "misc:woe_adm0":23424775,
    "misc:woe_adm1":2344924,
    "misc:woe_adm2":29375198,
    "misc:woe_lau":0,
    "misc:woe_local":3534,
    "misc:woe_ver":"7.10.0",
```

I suspect that any `misc:woe_` property should be a `woe:` property, and any `misc:gn_` property should be a `gn:` property. As for the others, I'm not entirely sure.

Dive into the `misc:*` properties, create a property lookup table and propose a PR.

**Comment by stepps00** [comment]
The following command:

`grep -r '"misc:' /usr/local/mapzen/whosonfirst-data/data > ~/Desktop/misc.txt`

returned the following unique `misc:*` properties:

```
misc:gn_adm0_cc
misc:gn_id
misc:gn_local
misc:gn_nam_loc
misc:gn_namadm1
misc:local_max
misc:local_sum
misc:localhoods
misc:name
misc:name_adm0
misc:name_adm1
misc:name_adm2
misc:name_local
misc:photo_max
misc:photo_sum
misc:placetype
misc:quad_count
misc:woe_adm0
misc:woe_adm1
misc:woe_adm2
misc:woe_funk
misc:woe_lau
misc:woe_local
misc:woe_ver
misc:gn_adm0_cc
misc:gn_fcode
misc:gn_name
misc:woeid
misc:name_lau
misc:name_en
```

**Comment by stepps00** [comment]
I suspect this is true, though I'm unsure of some of these properties...

```
misc:gn_adm0_cc    ->    gn:adm0_cc
misc:gn_id         ->    gn:id
misc:gn_local      ->    gn:local
misc:gn_nam_loc    ->    gn:nam_loc
misc:gn_namadm1    ->    gn:namadm1
misc:local_max     ->    ???
misc:local_sum     ->    ???
misc:localhoods    ->    ???
misc:name          ->    name:unk_x_variant
misc:name_adm0     ->    ???
misc:name_adm1     ->    ???
misc:name_adm2     ->    ???
misc:name_local    ->    name:unk_x_variant
misc:photo_max     ->    ???
misc:photo_sum     ->    ???
misc:placetype     ->    ???
misc:quad_count    ->    ???
misc:woe_adm0      ->    woe:adm0
misc:woe_adm1      ->    woe:adm1
misc:woe_adm2      ->    woe:adm2
misc:woe_funk      ->    woe:funk
misc:woe_lau       ->    woe:lau
misc:woe_local     ->    woe:local
misc:woe_ver       ->    woe:ver
misc:gn_adm0_cc    ->    gn:adm0_cc
misc:gn_fcode      ->    gn:fcode
misc:gn_name       ->    gn:name
misc:woeid         ->    woe:id
misc:name_lau      ->   ???
misc:name_en       ->    meso:name_en  
```

**Comment by nvkelso** [comment]
I suspect most of these are from a **quattroshapes** import for neighbourhoods (`local_max` and others).

One option is to re-prefix these to `qs:` (instead of `misc:`), and then additionally map some of them into concordances and other properties.

**Comment by stepps00** [comment]
I propose we update the `misc:*` properties as follows, let me know your thoughts:

**WOE**
`misc:woe_adm0`    ->    `woe:adm0`
`misc:woe_adm1`    ->    `woe:adm1`
`misc:woe_adm2`    ->    `woe:adm2`
`misc:woe_funk`    ->    `woe:funk`
`misc:woe_lau`    ->    `woe:lau`
`misc:woe_local`    ->    `woe:local`
`misc:woe_ver`    ->    `woe:ver`

**GN**
`misc:gn_adm0_cc`    ->    `gn:adm0_cc`
`misc:gn_local`    ->    `gn:local`
`misc:gn_namadm1`    ->    `gn:namadm1`
`misc:gn_adm0_cc`    ->    `gn:adm0_cc`
`misc:gn_fcode`    ->    `gn:fcode`
`misc:gn_name`    ->    `gn:name`

**QS**
`misc:local_max`    ->    `qs:local_max` 
`misc:local_sum`    ->    `qs:local_sum` 
`misc:localhoods`    ->    `qs:localhoods`
`misc:name_adm0`    ->    `qs:name_adm0` 
`misc:name_adm1`    ->    `qs:name_adm1` 
`misc:name_adm2`    ->    `qs:name_adm2` 
`misc:photo_max`    ->    `qs:photo_max` 
`misc:photo_sum`    ->    `qs:photo_sum` 
`misc:placetype`    ->    `qs:placetype` 
`misc:quad_count`    ->    `qs:quad_count`
`misc:name_lau`    ->   `qs:name_lau`


**Names**
`misc:name`    ->    append to `name:unk_x_variant`
`misc:name_local`    ->    append to `name:unk_x_variant`

**Multiple**
`misc:woeid`    ->    `qs:woe_id` and WOE `wof:concordances` value
`misc:name_en`    ->    `meso:name_en` and append to `name:eng_x_variant`
`misc:gn_id`    ->    `gn:id` and GeoNames `wof:concordances` value
`misc:gn_nam_loc`    ->    `gn:nam_loc` and append to `name:unk_x_variant`

**Comment by nvkelso** [comment]
In the Quattroshapes context `local` = locality due to DBF column name clipping.

**QS**
`misc:woe_adm0`    ->    `qs:woe_adm0`
`misc:woe_adm1`    ->    `qs:woe_adm1`
`misc:woe_adm2`    ->    `qs:woe_adm2`
`misc:woe_funk`    ->    `qs:woe_funk` (potentially `mz:is_funky`, but would need investigation)
`misc:woe_lau`    ->    `qs:woe_lau`
`misc:woe_local`    ->    `qs:woe_local`
`misc:woe_ver`    ->    `qs:woe_ver`
`misc:gn_adm0_cc`    ->    `qs:gn_adm0_cc`
`misc:gn_local`    ->    `qs:gn_local`
`misc:gn_namadm1`    ->    `qs:gn_namadm1`
`misc:gn_nam_loc`    ->    `qs:gn_nam_loc`
`misc:gn_adm0_cc`    ->    `qs:gn_adm0_cc`
`misc:placetype`    ->    `qs:placetype` (this is the GeoPlanet / WOE placetype)
`misc:name_adm0`    ->    `qs:name_adm0` (from GeoPlanet)
`misc:name_adm1`    ->    `qs:name_adm1` 
`misc:name_adm2`    ->    `qs:name_adm2` 
`misc:name_lau`    ->   `qs:name_lau`
`misc:name_local`    ->    `qs:name_local`
`misc:photo_max`    ->    `qs:photo_max` (invented by Quattroshapes)
`misc:photo_sum`    ->    `qs:photo_sum` 
`misc:local_max`    ->    `qs:local_max` 
`misc:local_sum`    ->    `qs:local_sum` 
`misc:localhoods`    ->    `qs:localhoods` (this is the total number of neighbourhoods in the parent locality reported both for the locality and the child neighbourhoods)
`misc:quad_count`    ->    `qs:quad_count`

**Names**
`misc:name`    ->    `qs:name` and append to `name:unk_x_variant` (if not there already; it's probably already the `wof:name`)
`misc:name_en`    ->    `qs:name_en` and append to `name:eng_x_variant` (if not there already)

**Multiple**
`misc:woeid`    ->    `qs:woeid`, and **gp** `wof:concordances` value
`misc:gn_id`    ->    `qs:gn_id`, `gn:id` and **gn** `wof:concordances` value
`misc:gn_fcode`    ->    `qs:gn_fcode` and `gn:fcode`
`misc:gn_name`    ->    `qs:gn_name` and `gn:name`
