### ISSUE TITLE
Records w/o hierarchies

### ISSUE THREAD

**Issue by trescube** [whosonfirst-data/whosonfirst-data#922]
Attached is a file of neighbourhood, locality, localadmin, county, and region WOF records that don't have hierarchies.  
[no_hierarchy.txt](https://github.com/whosonfirst-data/whosonfirst-data/files/1271740/no_hierarchy.txt)

**Comment by stepps00** [comment]
With all the recent PIP work completed in #824 and #980, the majority of cases have been fixed. 

I crawled the `whosonfirst-data` repository to find records at any admin placetype that had a `wof:hierarchy` of `[]` (or no `wof:hierarchy` property at all). There are ~360 records that need updated hierarchies ([list of records](https://github.com/whosonfirst-data/whosonfirst-data/files/1489169/null_hierarchies.txt)). Since any potential descendant records also need to have their hierarchies updated, the best action is to create a new pull request to run these records through the PIP tools.
