### ISSUE TITLE
restore deleted hierarchy

### ISSUE THREAD

**Issue by missinglink** [whosonfirst-data/whosonfirst-data#954]
The record for [Nouméa](https://whosonfirst.mapzen.com/spelunker/id/890413117/) previously had a hierarchy, at some point it was deleted (although it still shows in the spelunker).

It would be really helpful if we could restore the hierarchy, the alternative approach of building a graph from `parent_id` properties is far less convenient.

**Comment by missinglink** [comment]
It would be great to have an acceptance test in place that checks for records with a valid `wof:parent_id` but an empty `wof:hierarchy`. (this shouldn't really be possible)

PIP-ing can be avoided for these records by simply copying the hierarchy info from the parent to the child and then adding itself to the hierarchy.

**Comment by missinglink** [comment]
It seems like this issue is much more widespread than I initially thought, it appears to affect a large amount of `dependency` records (if not all of them?).

@stepps00 this issue is starting to cause some headaches to our acceptance tests, would it be possible to get a timeline for restoring the hierarchies for dependency records?

thanks!

**Comment by thisisaaronland** [comment]
These two issues might be related, so we'll see what things look like when the updates for issue #949 land...

https://github.com/whosonfirst-data/whosonfirst-data/issues/949

**Comment by nvkelso** [comment]
Generally speaking hierarchies are maintained during PIP process – there are a few exceptions that @stepps00 does curate and marks as controlled but that's not the case here.

**Comment by dianashk** [comment]
Related to https://github.com/pelias/placeholder/issues/54

**Comment by stepps00** [comment]
Dependency records were recently updated in https://github.com/whosonfirst-data/whosonfirst-data/pull/763/files. The updates removed the `country_id` from any dependency record because hierarchies of a dependency record should only include the dependency (itself), its empire, and its continent (see: https://github.com/whosonfirst-data/whosonfirst-data/issues/750).

These dependency records (and descendant records) were updated in https://github.com/whosonfirst-data/whosonfirst-data/commit/dd0dc23e29b0dbfb8378a625ebc99deb19d78aa0, but the pipeline tools handled assumptions at the `country`/`empire` level in a way that caused some hierarchies to be stripped.

@thisisaaronland and I chatted about this, and https://github.com/whosonfirst-data/whosonfirst-data/pull/915 was opened to fix this issue by adding `continent_ids` to the empire hierarchies. This has been merged, so I can file a PR that updates all dependency records - on paper, this should rebuild all dependency (and dependency records) as expected. I'll updated this issue once a new PR is created.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/980 has been opened, it should restore the hierarchies of dependency records and their descendants. If that does not fix the issue, the dependency records can be hand-edited and PIP'd.

**Comment by stepps00** [comment]
Noting here that the record for [Nouméa](https://whosonfirst.mapzen.com/spelunker/id/890413117/) has a hierarchy, as do the other `dependency` records. 

Leaving this issue open, still a WIP.
