### ISSUE TITLE
Issues with Lagos, Nigeria -- descendants & hierarchies

### ISSUE THREAD

**Issue by burritojustice** [whosonfirst-data/whosonfirst-data#960]
Region of Lagos shows no descendants:
https://whosonfirst.mapzen.com/spelunker/download/85675343/?exclude=nullisland

Lagos county shows no hierarchy:
https://whosonfirst.mapzen.com/spelunker/id/1108563887/

Municipality of Lagos shows no hierarchy:
https://whosonfirst.mapzen.com/spelunker/id/890437281/

**Comment by nvkelso** [comment]
Once he's back from vacation @stepps00 can take a look...

**Comment by stepps00** [comment]
Looks like the `wof:parent_id` of [the region of Lagos](https://whosonfirst.mapzen.com/spelunker/id/85675343/) was reset to `-1` [this commit](https://github.com/whosonfirst-data/whosonfirst-data/commit/177888be126d735627ca2aed23fc5b54ba223c28#diff-e1fe07bd02227f5bb5bf1bd9962aa09f) because of a lat/long not falling within the boundary of Nigeria. I suspect this trickled down "null" hierarchies to descendant records.

I will file a new PR with a new `reversegeo:latitude` and `reversegeo:longitude`properties for the Lagos region record, which should allow us to PIP the descendant records to update their missing hierarchies.

**Comment by stepps00** [comment]
This is actually "fixed", though the `wof:parent_id` for the record of Lagos is still `-1`.

I'd like to fix this using Boundary Issues; https://github.com/whosonfirst/whosonfirst-www-boundaryissues/issues/332 has been opened to track some funky-ness around the `wof:parent_id` property rebuilding.

**Comment by stepps00** [comment]
Lagos now has `reversegeo:latitude` and `reversegeo:longitude` properties to ensure this records falls within Nigeria: https://github.com/whosonfirst-data/whosonfirst-data/commit/f573552cbfc179fe2ab44c57f2f2f4f736f646e3

**Comment by nvkelso** [comment]
Noting here that really the Nigeria shape needs a revgeo polygon to avoid
the whole lagoon / coastline problem in the first place...

**Comment by stepps00** [comment]
The original three issues listed in https://github.com/whosonfirst-data/whosonfirst-data/issues/960#issue-260417373 have been fixed. I've also updated the `region` record of Lagos in a recent commit to fix the `wof:parent_id`. 

To fix https://github.com/whosonfirst-data/whosonfirst-data/issues/960#issuecomment-334551457, I've opened https://github.com/whosonfirst-data/whosonfirst-data/pull/1017.

A comparison of the country geometry (light green) and the new reversegeo geometry (dark green). All coastal inlets have been filled in.

<img width="1340" alt="screen shot 2017-10-25 at 10 28 29 am" src="https://user-images.githubusercontent.com/18567700/32014963-74e8b576-b974-11e7-957e-7ea000cdc178.png">
