### ISSUE TITLE
Look for more complete data for Peru localities, such as Chinchero

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#965]
This came in through support (see Desk 888). I'm not sure if there is a dataset out there that we could import, but wanted to log this for the user.

No results in Peru for Chinchero: https://whosonfirst.mapzen.com/spelunker/search/?q=Chinchero

--

"The Chinchero district/locality in Peru's Urubamba province isn't listed at all in wof. I think it should probably be a locality.

https://mapzen.com/search/explorer/?query=search&text=Chinchero&sources=wof

Here is the wikipedia page for Chinchero,
https://en.wikipedia.org/wiki/Chinchero_District

Note that Chinchero is different to Chincheros which is a province in its
own right and is listed in wof.
https://en.wikipedia.org/wiki/Chincheros_Province"

**Comment by stepps00** [comment]
Yeah, it looks like we are missing the `locality` (district) of Chinchero, Peru. I will take a look in the open PRs, as a new `locality` record for Chinchero could be waiting for import.. otherwise, I'll look for another open dataset for Peru localities so we can import a new record.

Peru, by placetype:

Division | Official Name | WOF placetype
--- | --- | ---
First-level | Region | region
Second-level | Province | county
Third-level | District | locality

**Comment by stepps00** [comment]
This record is in the upcoming GeoNames import.

Related: #108.

**Comment by stepps00** [comment]
#108 landed, which brought in a new record for Chinchero: https://raw.githubusercontent.com/whosonfirst-data/whosonfirst-data/master/data/132/731/845/7/1327318457.geojson
