### ISSUE TITLE
85902801 (neighbourhood Santa Clara) in Manila does not have Manila as its locality

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#966]
This neighbourhood: https://whosonfirst.mapzen.com/spelunker/id/85902801/

It's clearly in Manila - and the "misc" properties on the record list Manila - but it's locality value in the hierarchy is set to -1.

**Comment by stepps00** [comment]
Hey @simonw, thanks for filing the issue. Two issues going on here..

First, [Manila](https://whosonfirst.mapzen.com/spelunker/id/421168919/) won't be in this neighbourhood's hierarchy because Manila has a point geometry.

Second, the latitude and longitude values used for PIP work fell outside of (what should be) it's parent geometries. I used Boundary Issues to add `reversegeo:latitude` and `reversegeo:longitude` properties and rebuild the record's hierarchy. This worked, and you can view the changes in the record: https://whosonfirst.mapzen.com/spelunker/id/85902801/

I will copy the change commit shortly, then close this issue.

**Comment by stepps00** [comment]
Commit: https://github.com/whosonfirst-data/whosonfirst-data/commit/89fd13157255cd9880bbcf1c311b44ab674eca1d
