### ISSUE TITLE
Potentially duplicate locality features for Tiranë and Tirana in Albania

### ISSUE THREAD

**Issue by rmglennon** [whosonfirst-data/whosonfirst-data#983]
This came in through support (see Desk 1126) from a user working with Mapzen Search.

"Tirana, Albania and Tiranë, Albania both return distance Who's on First
records? But they should be (and appear to be) referencing the same city,
is this intended?"

It looks like the records for Tirana and Tiranë may be overlapping. Here are the spelunker records.

https://whosonfirst.mapzen.com/spelunker/id/421187037/
https://whosonfirst.mapzen.com/spelunker/id/890444545/

These should be reviewed, and potentially merged, so that these are alternative names for the same locality.

**Comment by stepps00** [comment]
Yeah, these are duplicate `locality` records for Tirana, Albania. Since these are both point geometries, no geometry merging is needed.

This is a good candidate for Boundary Issues - I'll deprecate and supersede one record into the other and bring over any properties. I'll follow-up with commits and close the issue once resolved.

**Comment by stepps00** [comment]
Opened https://github.com/whosonfirst-data/whosonfirst-data/pull/984 rather than updating in BI.

**Comment by stepps00** [comment]
@rmglennon - the PR for this issue has been merged and will be seen in production shortly. If the user still has issues, feel free to re-open.
