### ISSUE TITLE
Locality of Hong Kong has no polygon (any others?), so it's never returned by getHierarchiesByLatLon

### ISSUE THREAD

**Issue by simonw** [whosonfirst-data/whosonfirst-data#993]
The locality of Hong Kong is a point geometry - it does not have a polygon defined: https://whosonfirst.mapzen.com/spelunker/id/890437279/

This means that it's never returned by queries to the getHierarchiesByLatLon API - instead we get back results like these:

    [
        {
            "parent_id": null, 
            "id": "102191569", 
            "place_type": "continent", 
            "name": "Asia"
        }, 
        {
            "parent_id": "102191569", 
            "id": "85632483", 
            "place_type": "country", 
            "name": "Hong Kong S.A.R."
        }, 
        {
            "parent_id": "85632483", 
            "id": "85671791", 
            "place_type": "region", 
            "name": "Yau Tsim Mong"
        }, 
        {
            "parent_id": "85671791", 
            "id": "85908029", 
            "place_type": "neighbourhood", 
            "name": "\u8001\u6f58"
        }
    ]

This is bad, because it means that we're not resolving any of our points to being within that locality.

I imagine there is already a goal to get a real polygon in place for this locality. What would be incredibly helpful for me though is if I could get a list of any other localities that have a point representation as opposed to a polygon. This would allow me to special-case them in the app I am building.

**Comment by thisisaaronland** [comment]
I probably won't be able to get to this (adding it to the API) today but you can see the list in the Spelunker here:

https://whosonfirst.mapzen.com/spelunker/placetypes/locality/?geometry=point

Are you looking to have this information returned as an `extras` parameter or to filter on it or both?

**Comment by thisisaaronland** [comment]
Also, note that there is an open PR with all (most?) of the remaining "point-only" data from Quattroshapes that is about to land in `master` so that number will be enbiggened.

**Comment by nvkelso** [comment]
We're discussing for any neighbourhood polygon we can create locality polygons using all the children in: https://github.com/whosonfirst-data/whosonfirst-data/issues/106.

This issue is suggesting we may want to add a `1 km by 1 km` fake polygon from a buffer around the point marked mz:is_approximate?

**Comment by thisisaaronland** [comment]
The ghosts of Where On Earth (which was littered with 1km square boxes...) ride again ;-)

**Comment by nvkelso** [comment]
1km square boxes, riding again like one of the 5 riders of the (geo) apocalypse ;)

**Comment by simonw** [comment]
@thisisaaronland that link is all I needed - I don't need to be able to pull these from an API (I'm sure I could Chrome-debug-tools them out of the Spelunker if I really need to)

**Comment by thisisaaronland** [comment]
this is why I ❤️ you @simonw - it's a useful filter so we'll add it to the API shortly, anyway :-)

**Comment by simonw** [comment]
I think this is the same underlying issue as the Cartagena one I reported last week #977

**Comment by stepps00** [comment]
The locality record for Hong Kong ([here](https://github.com/whosonfirst-data/whosonfirst-data/blob/master/data/890/437/279/890437279.geojson)) now has a polygon, added through #1496 when updating capital city polygons.

There is a bit of follow up work around dual hierarchies and other locality points being tracked through #1549. I'm going to close this issue since Hong Kong now has a polygon and will track other updates in the new issue.
